### ISSUE TITLE
Error: Element 'tags' must not contain child elements

### ISSUE THREAD

**Issue by iljapavlovs** [temyers/cucumber-jvm-parallel-plugin#101]
Stumbled upon an issue when putting <tag> in <tags>
E.g.:
```
<tags>
    <tag>@regression</tag>
</tags>
```

Error output:
`[ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:2.2.0:generateRunners (generateRunners) on project cucumber-java-skeleton: Unable to parse configuration of mojo com.github.temyers:cucumber-jvm-parallel-plugin:2.2.0:generateRunners: Basic element 'tags' must not contain child elements`

**Comment by mpkorstanje** [comment]
Whoops. You are looking at the documentation for an upcoming release. Please check here for the latest:

https://github.com/temyers/cucumber-jvm-parallel-plugin/tree/62d8fd252f86619f522a528af1a1d310267bd8ec
