### ISSUE TITLE
version 4.0.0 issue with generating runner

### ISSUE THREAD

**Issue by misko-frame** [temyers/cucumber-jvm-parallel-plugin#109]
I have following configuration for glue:
....
<glue>						
   <package>me.test.panel.steps</package>
   <package>me.test.panel.base.steps</package>
</glue>
....

and plugin is generating following runner:
//Parallel01IT ->Content:
import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions(
        // not important
        glue = {"me.test.panel.steps", **"\n\t\t\t\t\t\t\t\tme.test.panel.base.steps"**})
public class Parallel01IT {
}

Problem:
all methods from me.test.panel.steps are executing, but code from me.test.panel.base.steps is not executing

This was working in 2.2.0.
(...
<glue>
 me.test.panel.steps,
 me.test.panel.base.steps
</glue>
...)

One additional detail, I am using mac while trying to run this configuration.
Any advice on this?
Thanks,
Milos

**Comment by mpkorstanje** [comment]
Does your glue look like this:
```
        <glue>
          <package>me.test.panel.steps</package>
          <package>me.test.panel.base.steps</package>
        </glue>
```
Or like this:
```
        <glue>
          <package>
                           me.test.panel.steps</package>
          <package>
                           me.test.panel.base.steps</package>
        </glue>
```

**Comment by misko-frame** [comment]
<glue>
          <package>me.test.panel.steps</package>
          <package>me.test.panel.base.steps</package>
</glue>

**Comment by misko-frame** [comment]
<glue>
          <package>me.test.panel.steps</package>
          <package>me.test.panel.base.steps</package>
        </glue>

**Comment by mpkorstanje** [comment]
Can you copy the section from your pom?

**Comment by misko-frame** [comment]
`<glue> \n
          <package>me.test.panel.steps</package> \n
          <package>me.test.panel.base.steps</package> \n
 </glue>`

**Comment by misko-frame** [comment]
> <glue>
          <package>me.test.panel.steps</package>
          <package>me.test.panel.base.steps</package>
 </glue>

**Comment by mpkorstanje** [comment]
Thanks. Can you show the whole section from `<plugin>` to `</plugin>`?

**Comment by misko-frame** [comment]
> <build>
			<plugin>
				<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>4.0.0</version>
				<executions>
					<execution>
					<?m2e execute onConfiguration?>
						<id>generateRunners</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>generateRunners</goal>
						</goals>
						<configuration>
							
							
							<glue>
								<package>me.test.panel.steps</package>
      							<package>me.test.panel.base.steps</package>
							</glue>
							
							
							<outputDirectory>target/cucumber-parallel/generated-test-sources/cucumber</outputDirectory>
							
							<featuresDirectory>src/test/resources/features/Performance</featuresDirectory>
							
							<cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
							<tags>
								<tag>@CP_LOGIN</tag>
								<tag>@CP_BASIC_SESSION_HANDLING_LAUNCHPAD</tag>
							</tags>
							<filterFeaturesByTags>true</filterFeaturesByTags>
							
							
							
							<parallelScheme>SCENARIO</parallelScheme>
							
							
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<configuration>
					<forkCount>20</forkCount>
					<reuseForks>true</reuseForks>
					<includes>
						<include>**/*IT.class</include>
					</includes>
				</configuration>
			</plugin>

		</plugins>

	</build>

**Comment by mpkorstanje** [comment]
Your plugin configuration looks correct. 

Two plausible options
 * I am seeing m2e annotations. Are you using m2e through eclipse? 
 * Are you passing glue through cucumber options anywhere?

If yes to either, please try without. If both questions can be answered with no then there is no plausible way that I can see for the whitespace to end up the glue. Which also means I'm out of ideas. 

Please clone this repository, create a minimal example based on the [simple integration test](
https://github.com/temyers/cucumber-jvm-parallel-plugin/tree/master/src/it/junit/simple-it) that reproduces the problem for you.

**Comment by misko-frame** [comment]
1.It's working without 

> <?m2e execute onConfiguration?> ->(I found this quick fix somewhere on stackoverflow)

but I am getting 
Plugin execution not covered by lifecycle configuration: com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners (execution: generateRunners, phase: generate-test-sources)	/panel-tests	pom.xml	line 75	Maven Project Build Lifecycle Mapping Problem

2.when I try exactly the same pom config on win10 machine there is no error

**Comment by mpkorstanje** [comment]
And if you try it from the command line? Eclipse does things with maven.

Works for me on unix btw.

**Comment by mpkorstanje** [comment]
Excelent! You're welcome!
