### ISSUE TITLE
Using the plugin within a jenkins build

### ISSUE THREAD

**Issue by Fraser1994** [temyers/cucumber-jvm-parallel-plugin#110]
Hi I am getting the following error when building my project with jenkins:

> Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners (generateRunners) on project MGM-Automation: Unable to parse configuration of mojo com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners for parameter tags: Cannot assign configuration entry 'tags' with value '@CM15error' of type java.lang.String to property of type java.util.List

The project works when I build it locally. Any suggestions as to how I can resolve this?

**Comment by mpkorstanje** [comment]
Please ensure that on both Jenkins and and your local machine the tags element looks like this:

```xml
<tags>
          <tag>@CM15error</tag>
</tags>
```

From the error I'm guessing that on Jenkins it looks like this:

```xml
<tags>@CM15error</tags>
```

**Comment by Fraser1994** [comment]
That's solved it, thanks for the super quick response!!!
