### ISSUE TITLE
Customising generated reports to the feature/testrunner name

### ISSUE THREAD

**Issue by Fraser1994** [temyers/cucumber-jvm-parallel-plugin#111]
I saw #80 about having reports have system info instead of the fork number. I don't want to use system info but instead wondered if there is an easy way to implement the feature/testrunner name being the generated reports name?

**Comment by mpkorstanje** [comment]
1. If you are using the feature-title or pattern naming scheme then the name of the feature or scenario in the report should match that.

2. You can use a `customVmTemplate` to generate your own runners that set or store the test name in some way. 

Otherwise no.

**Comment by Fraser1994** [comment]
I am using a pattern naming scheme with a customVmTemplate. I have the name of the generated feature file stored as a parameter. But the default behavior is to output reports with the name as {1}.json... where {no} is the number of the thread the feature ran in

**Comment by mpkorstanje** [comment]
Ah I misunderstood! You want to correlate the json file name rather then its contents to the test runner. Currently it is not possible. Though I suppose you could hack it by adding the json plugin and desired output file in the template.

The proper way would be refactoring [Plugin.asPluginString](https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/main/java/com/github/timm/cucumber/generate/Plugin.java#L125) to use a strategy and submitting it as PR.
