### ISSUE TITLE
Plugin execution not covered by lifecycle configuration:

### ISSUE THREAD

**Issue by benz-philip** [temyers/cucumber-jvm-parallel-plugin#113]
![screen shot 2017-05-11 at 4 59 51 pm](https://cloud.githubusercontent.com/assets/18724283/25950293/78d52eb2-366b-11e7-8b70-dc0af42a2ee8.png)

May I know how to resolve this?

**Comment by mpkorstanje** [comment]
Everything should work if you use the command line. IntelliJ IDEA also seems to work fine.

If you must use Eclipse please read this:

https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html

You can either ignore the goal or create a pull request that adds the metadata needed by m2e.

**Comment by benz-philip** [comment]
@mpkorstanje Thank you very much! I ignored the error and its working fine now.

**Comment by poojaadari** [comment]
@benz-philip : Could you please explain on how you resolved this. I'm new to maven and couldn't figure out the solution from the help above.
