### ISSUE TITLE
Multiple folders under features

### ISSUE THREAD

**Issue by vanatomas** [temyers/cucumber-jvm-parallel-plugin#114]
Hello, I could not find info on such.
I have resources->featureFiles where I have several folders, depends on are of testing that contain feature files. 
Does this plugin support such structure or all feature files should be under featureFiles folder?
Thank you

**Comment by mpkorstanje** [comment]
Right now we support we only support a single features directory. All features must be in a subdirectory of that features directory. E.g:

```
featuresDirectory/
 |- widget-can-fidget.feature
 |- fidget-can-widget.feature
 |- the-widget-project/ 
 |  |- widget-can-fidget.feature
 |  |- fidget-can-widget.feature
```

**Comment by vanatomas** [comment]
right, that what I meant, I have subfolders under feature folder, so that will work, awesome, thank you
