### ISSUE TITLE
Add ability to select multiple feature folders and files

### ISSUE THREAD

**Issue by noead01** [temyers/cucumber-jvm-parallel-plugin#115]
Hello,

It would be great if the plugin supported specifying multiple feature folders and files, since cucumber options support them.

The use case is the following:
My feature files are organized by feature groups, like features/group1, features/group2, features/group3 and so on. In cucumber options, I can specify multiple feature folders if I want to run only group1 and group3, I just add "features/group1 features/group3" to my cucumber options, and it does not run group2 features.

I realize that I could also use tags to filter the features, but it seems unnecessarily (cu)cumbersome.

Thanks for considering.

**Comment by mpkorstanje** [comment]
Contributions are welcome!
