### ISSUE TITLE
Double tag not working 

### ISSUE THREAD

**Issue by gaponte1985** [temyers/cucumber-jvm-parallel-plugin#117]
<tags>
                        <tag>@billing</tag>
                        <tag>~@billing</tag>
                        <tag>@important</tag>
                        <tag>@important,@billing</tag>
                    </tags>
<img width="354" alt="screen shot 2017-05-15 at 3 16 48 pm" src="https://cloud.githubusercontent.com/assets/996659/26074980/ada5c67e-3981-11e7-9aaa-81b44698eef7.png">

**Comment by mpkorstanje** [comment]
Please see:

http://stackoverflow.com/questions/4056140/maven-resource-filtering-implications-of-the-symbol-in-resource-files

**Comment by temyers** [comment]
What are you actually trying to do?

Note that the examples above are mutually exclusive: see https://github.com/cucumber/cucumber/wiki/Tags
