### ISSUE TITLE
Plugging json and path.to.my.formaters.NoOutputFormatte not working

### ISSUE THREAD

**Issue by gaponte1985** [temyers/cucumber-jvm-parallel-plugin#118]
<img width="812" alt="screen shot 2017-05-15 at 3 08 58 pm" src="https://cloud.githubusercontent.com/assets/996659/26075039/dc7b683c-3981-11e7-87b0-21b2e9c5cd84.png">

**Comment by gaponte1985** [comment]
<img width="1022" alt="screen shot 2017-05-15 at 3 08 49 pm" src="https://cloud.githubusercontent.com/assets/996659/26075043/e5ebdc08-3981-11e7-9fa7-7d9d2d4acd65.png">
<img width="1644" alt="screen shot 2017-05-15 at 3 08 33 pm" src="https://cloud.githubusercontent.com/assets/996659/26075049/ec59c816-3981-11e7-9d3c-6b78f1f180a9.png">

**Comment by mpkorstanje** [comment]
I have two integration tests to proof that they they work. :D

https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/custom-plugins/pom.xml
https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/custom-plugin-no-output/pom.xml

Please ensure that the plugins are within the configuration section of cucumber-jvm-parallel-plugin.

**Comment by temyers** [comment]
Your `<plugin>` definition is invalid: you are not using the cucumber-jvm-parallel-plug.  Please see the README.

**Comment by gaponte1985** [comment]
<img width="1648" alt="screen shot 2017-05-15 at 10 03 33 pm" src="https://cloud.githubusercontent.com/assets/996659/26086746/8da62f1a-39ba-11e7-892d-464d06156543.png">
yes
