### ISSUE TITLE
Plugin has problems generating test sources on Bamboo with Ubuntu Agent

### ISSUE THREAD

**Issue by Deepthirh** [temyers/cucumber-jvm-parallel-plugin#119]
When the maven command is run on bamboo with Ubuntu agent, the plugin does not generate any test sources for the configuration.

It runs without any issues when run on local machine, for ex: debian, mac, windows etc...

Please find the maven plugin config below:

		      <plugin>
		        <groupId>com.github.temyers</groupId>
		        <artifactId>cucumber-jvm-parallel-plugin</artifactId>
		        <version>4.1.0</version>
		        <executions>
		          <execution>
		            <id>generateRunners</id>
		            <phase>generate-test-sources</phase>
		            <goals>
		              <goal>generateRunners</goal>
		            </goals>
		            <configuration>
		              <glue>
		                <package>com.test.java.cucumber</package>
		              </glue>
		              <featuresDirectory>src/test/resources/features/</featuresDirectory>
		              <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
		                      <plugins>
		                <plugin>
		                    <name>json</name>
		                </plugin>
		                <plugin>
		                    <name>html</name>
		                </plugin>
		                  </plugins>
		                  <tags>
		                    <tag>${tags}</tag>
		                    <tag>${ignoreTags}</tag>
		                  </tags>
		                <strict>true</strict>
		              
		              <useTestNG>false</useTestNG>
		              
		              <namingScheme>pattern</namingScheme>
		              
		              <namingPattern>Parallel{c}CT</namingPattern>
		              
		              <parallelScheme>${parallelScheme}</parallelScheme>
		              
		              <customVmTemplate>src/test/resources/cucumber-mytest-junit-runner.vm</customVmTemplate>
		              <packageName>com.test.java.cucumber</packageName>
		            </configuration>
		          </execution>
		        </executions>
		      </plugin>

The **_target_** directory listing on ubuntu bamboo agent is as follows:
target/generated-test-sources/cucumber:
total 0
drwxr-xr-x. 3 root root 24 May 19 22:11 com

target/generated-test-sources/cucumber/com:
total 0
drwxr-xr-x. test

target/generated-test-sources/cucumber/com/test:
total 0
drwxr-xr-x. java

target/generated-test-sources/cucumber/com/test/java:
total 0
drwxr-xr-x. cucumber
	
target/generated-test-sources/cucumber/com/test/java/cucumber:
total 0

The **_com.test.java.cucumber_** package doesn't have any classes generated in it.

I can see the the plugin has run during the `mvn clean install`
I tried to get the debug logs by passing -X but did not find anything useful from the plugin so can't tell why the runners are not generated on run time on bamboo remote agent (Ubuntu 16)

Can you please try pointing out the issue and help in fix it?

**Comment by mpkorstanje** [comment]
Likely cause is tags. If no test matches tags, no runners are generated. I assume tags are different on build server from local machine.

Logging could definitly be improved.

**Comment by Deepthirh** [comment]
I have made sure that the right code is checked in and the tags are correct.

for example : clean generate-test-sources  -X -Dtags="@smoke " -DignoreTags="~@test21"

The above command generates runner classes and works absolutely fine on local systems like windows , MAC , Debian.
But when run using bamboo the runner classes are not generated

**Comment by Deepthirh** [comment]
The only thing I can think of is bamboo has problems with -D properties with double quotes ""
I will remove the quotes any try on Monday and update my findings if that helps.

**Comment by mpkorstanje** [comment]
Qoutes should not end up in pom. A shell removes them. Don't know about bamboo.

Should that fail your best option then would be to clone the repo and add the debug statements. Then run with your version of the plugin and see what it does.

**Comment by Deepthirh** [comment]
Sure I will give it a try. The agents are down over weekend. I will keep you posted. Thanks

**Comment by Deepthirh** [comment]
The issue is resolved. The problem was with quotes around the tags as I suspected.
Now the quotes are removed. When you run a maven command in bamboo, it’s does not interpolate or parse the quotes
New command:
clean generate-test-sources -X -Dtags=@smoke" -DignoreTags=~@test21

**Comment by mpkorstanje** [comment]
Excelent!
