### ISSUE TITLE
Malformed POM /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/pom.xml: Unrecognised tag: 'name' 

### ISSUE THREAD

**Issue by gaponte1985** [temyers/cucumber-jvm-parallel-plugin#120]
I am getting the following error please help me thanks 

ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.uhc.coretestautofrmwk:QAAutomation:1.0-SNAPSHOT (/Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/pom.xml) has 1 error
[ERROR]     Malformed POM /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/pom.xml: Unrecognised tag: 'name' (position: START_TAG seen ...estng, html, pretty, json, usage and rerun -->\n             <name>... @272:20)  @ /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/pom.xml, line 272, column 20 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
LAMU02TC0F2GTFM:com.uhc.coretestautofrmwk gaponte2$

**Comment by gaponte1985** [comment]
I have

<plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.5.1</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
            </configuration>
        </plugin>

        <plugin>
            <groupId>com.github.temyers</groupId>
            <artifactId>cucumber-jvm-parallel-plugin</artifactId>
            <version>4.0.0</version>
            <executions>
                <execution>
                    <id>generateRunners</id>
                    <phase>generate-test-sources</phase>
                    <goals>
                        <goal>generateRunners</goal>
                    </goals>
                    <configuration>
                        
                        
                        <glue>


                            <package>cukes.steps.frameworkshakeout.UI</package>
                            <package>cukes.hooks</package>
                            <package>utilities.hooks</package>
                            <package>cukes.steps.frameworkshakeout.API</package>


                        </glue>
                        
                        
                        <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
                        
                        <featuresDirectory>src/test/resources/features/</featuresDirectory>
                        
                        <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
                        
                        <plugins>
                            <plugin>
                                <name>json,html</name>
                            </plugin>
                            <plugin>
                                <name>com.example.CustomHtmlFormatter</name>
                                <extension>html</extension>
                            </plugin>
                        </plugins>
                        
                        <strict>true</strict>
                        
                        <monochrome>true</monochrome>
                        
                        <tags>
                            <tag>@Web</tag>
                            <tag>@API</tag>

                        </tags>
                        
                        <filterFeaturesByTags>false</filterFeaturesByTags>
                        
                        <useTestNG>false</useTestNG>
                        
                        <namingScheme>simple</namingScheme>
                        
                        <namingPattern>Parallel{c}IT</namingPattern>
                        
                        <parallelScheme>SCENARIO</parallelScheme>
                        
                        <customVmTemplate>src/test/resources/cucumber-custom-runner.vm</customVmTemplate>
                        
                        <packageName>com.example</packageName>
                    </configuration>
                </execution>
            </executions>
            
             <name>junit,html,pretty,json</name>
             
            <extension>json</extension>
            
            <outputDirectory>${project.build.directory}/cucumber-parallel/json</outputDirectory>

            <name>path.to.my.formaters.NoOutputFormatter</name>
            
            <noOutput>true</noOutput>
        </plugin>
    </plugins>
    </build>

**Comment by mpkorstanje** [comment]
The element `<name>junit,html,pretty,json</name>` shouldn't be there. You should probably remove it.

The element `<name>json,html</name>` also doesn't look right. Did you mean
```xml
<plugins>
    <plugin>
        <name>json</name>
    </plugin>
    <plugin>
        <name>html</name>
    </plugin>
</plugins>
```

**Comment by gaponte1985** [comment]
no is in the page 

Cucumber Plugins

Cucumber plugins that write to a file are referenced using the syntax name[:outputDirectory/excutorId[.extension]]. Because not all plugins create output and the excutorId is provided at runtime some leg work is needed.

Build-in Cucumber Plugins

<plugins>
    <plugin>
        
        <name>json</name>
        
        <extension>json</extension>
        
        <outputDirectory>${project.build.directory}/cucumber-parallel/json</outputDirectory>
    </plugin>
</plugins>


https://github.com/temyers/cucumber-jvm-parallel-plugin

**Comment by gaponte1985** [comment]
Cucumber Plugins

Cucumber plugins that write to a file are referenced using the syntax name[:outputDirectory/excutorId[.extension]]. Because not all plugins create output and the excutorId is provided at runtime some leg work is needed.

Build-in Cucumber Plugins

<plugins>
    <plugin>
        
        <name>json</name>
        
        <extension>json</extension>
        
        <outputDirectory>${project.build.directory}/cucumber-parallel/json</outputDirectory>
    </plugin>
</plugins>

https://github.com/temyers/cucumber-jvm-parallel-plugin

**Comment by mpkorstanje** [comment]
I know. I wrote that. Give my suggestion a try. :)

**Comment by gaponte1985** [comment]
still I have this

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.5.1</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
            </configuration>
        </plugin>
        <plugin>
            <groupId>com.github.temyers</groupId>
            <artifactId>cucumber-jvm-parallel-plugin</artifactId>
            <version>4.0.0</version>
            <executions>
                <execution>
                    <id>generateRunners</id>
                    <phase>generate-test-sources</phase>
                    <goals>
                        <goal>generateRunners</goal>
                    </goals>
                    <configuration>
                        
                        
                        <glue>
                            <package>cukes.steps.frameworkshakeout.UI</package>
                            <package>cukes.hooks</package>
                            <package>utilities.hooks</package>
                            <package>cukes.steps.frameworkshakeout.API</package>
                        </glue>
                        
                        
                        <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
                        
                        <featuresDirectory>src/test/resources/features/</featuresDirectory>
                        
                        <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
                        
                        <plugins>
                            <plugin>
                                <name>json,html</name>
                            </plugin>
                            <plugin>
                                <name>com.example.CustomHtmlFormatter</name>
                                <extension>html</extension>
                            </plugin>
                        </plugins>
                        
                        <strict>true</strict>
                        
                        <monochrome>true</monochrome>
                        
                        <tags>
                            <tag>@Web</tag>
                            <tag>@API</tag>

                        </tags>
                        
                        <filterFeaturesByTags>false</filterFeaturesByTags>
                        
                        <useTestNG>false</useTestNG>
                        
                        <namingScheme>simple</namingScheme>
                        
                        <namingPattern>Parallel{c}IT</namingPattern>
                        
                        <parallelScheme>SCENARIO</parallelScheme>
                        
                        <customVmTemplate>src/test/resources/cucumber-custom-runner.vm</customVmTemplate>
                        
                        <packageName>com.example</packageName>
                    </configuration>
                </execution>
            </executions>
            
            <plugin>
                    <name>json</name>
                </plugin>
                <plugin>
                    <name>html</name>
                </plugin>

            
            <extension>json</extension>
            
            <outputDirectory>${project.build.directory}/cucumber-parallel/json</outputDirectory>

            <name>path.to.my.formaters.NoOutputFormatter</name>
            
            <noOutput>true</noOutput>
        </plugin>
    </plugins>
    </build>

**Comment by gaponte1985** [comment]
LAMU02TC0F2GTFM:com.uhc.coretestautofrmwk gaponte2$ mvn clean
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.uhc.coretestautofrmwk:QAAutomation:1.0-SNAPSHOT (/Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/pom.xml) has 1 error
[ERROR]     Malformed POM /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/pom.xml: Unrecognised tag: 'plugin' (position: START_TAG seen ...stng, html, pretty, json, usage and rerun -->\n            <plugin>... @273:21)  @ /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/pom.xml, line 273, column 21 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
LAMU02TC0F2GTFM:com.uhc.coretestautofrmwk gaponte2$

**Comment by mpkorstanje** [comment]
All the configuration for cucumber-jvm-parallel have to be inside the `configuration` element. Note that the the cucumber cucumber-jvm-parallel is a maven plugin that uses plugins itself. I feel that you are confusing these two different kinds of plugins.

```xml
<plugins>
    <plugin>
        <name>json</name>
    </plugin>
    <plugin>
        <name>html</name>
    </plugin>
</plugins>
```

Should be inside the `configuration`. You also have several other configuration elements outside of the `configuration` element.

**Comment by gaponte1985** [comment]
ok thanks, knowing I passing another error 

[INFO] --- cucumber-jvm-parallel-plugin:4.1.0:generateRunners (generateRunners) @ QAAutomation ---
May 31, 2017 3:48:40 PM org.apache.velocity.runtime.log.JdkLogChute log
SEVERE: ResourceManager : unable to find resource 'src/test/resources/cucumber-custom-runner.vm' in any resource loader.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.107 s
[INFO] Finished at: 2017-05-31T15:48:40-04:00
[INFO] Final Memory: 15M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:4.1.0:generateRunners (generateRunners) on project QAAutomation: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:4.1.0:generateRunners failed: Unable to find resource 'src/test/resources/cucumber-custom-runner.vm' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by mpkorstanje** [comment]
Do you use a custom template?

**Comment by gaponte1985** [comment]
not sure what does it meant custom template? can you help me Clarify it. thanks

**Comment by mpkorstanje** [comment]
https://github.com/temyers/cucumber-jvm-parallel-plugin#custom-templates

**Comment by gaponte1985** [comment]
Yes I am using extender report, but not cucumber report Do I need the plugins in order to work>

**Comment by mpkorstanje** [comment]
You don't need json or html plugin. You do need ExtentCucumberFormatter plugin. See the example om and template:

https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/extents-report/pom.xml
https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/extents-report/src/test/resources/cucumber-extents-report-runner.java.vm

**Comment by gaponte1985** [comment]
what if i dont want to used template

**Comment by mpkorstanje** [comment]
Then you can't use extent reports. If you don't want to use those either, you don't include template configuration.

**Comment by gaponte1985** [comment]
it have to be  a file vm?

**Comment by mpkorstanje** [comment]
Yes. It has to be a virtual marker template.

You can however use any file name you like. If you have a proper IDE it will recoqnize `template.java.vm` as being both java and virtual marker.

**Comment by gaponte1985** [comment]
ok I just run it created a folder but is not running the test cases what should I do?

**Comment by gaponte1985** [comment]
so it create a folder with all the classes but is not running parallel testing so not sure what to do i am doing mvn clean and mvn install

**Comment by mpkorstanje** [comment]
Check this https://opencredo.com/running-cucumber-jvm-tests-in-parallel/

But your problems don't appear to be related to this plugin. So you should probably build up some experience with maven. Perhaps you can ask a coworker?

**Comment by hanikhan** [comment]
I was reading the thread as I am trying to do something similar. I got extent report to work with parallel plugin using the sample links you shared. However, I noticed that it generates individual HTML report for every runner. Is it possible to consolidate all the reports post execution

**Comment by mpkorstanje** [comment]
For now you can replace the plugin section in the template with:

```
plugin = {"com.cucumber.listener.ExtentCucumberFormatter:target/cucumber-parallel/my-test-reports.html"},
```

But I guess it would be better if aside from the dynamic output file a fixed output could be configured in the pom.
