### ISSUE TITLE
glue

### ISSUE THREAD

**Issue by gaponte1985** [temyers/cucumber-jvm-parallel-plugin#123]
I have try diferents type to input glue 

            <glue>com..corestautofrmwk.utilities.java.hooks, com..corestautofrmwk.test.cukes.steps.frameworkshakeout.API, com..corestautofrmwk.test.cukes.steps.frameworkshakeout.UI </glue>

<glue>utilities.java.hooks, cukes.steps.frameworkshakeout.API, 
cukes.steps.frameworkshakeout.UI </glue>

and  
<glue>utilities.java.hooks</glue> <glue> cukes.steps.frameworkshakeout.API </glue>
<glue>cukes.steps.frameworkshakeout.UI </glue>

and always get the same error message 

[INFO] 
[INFO] --- cucumber-jvm-parallel-plugin:4.1.0:generateRunners (generateRunners) @ QAAutomation ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.878 s
[INFO] Finished at: 2017-06-06T00:16:19-04:00
[INFO] Final Memory: 13M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:4.1.0:generateRunners (generateRunners) on project QAAutomation: Unable to parse configuration of mojo com.github.temyers:cucumber-jvm-parallel-plugin:4.1.0:generateRunners for parameter glue: Cannot assign configuration entry 'glue' with value 'com.uhc.corestautofrmwk.utilities.java.hooks, com.uhc.corestautofrmwk.test.cukes.steps.frameworkshakeout.API, com.uhc.corestautofrmwk.test.cukes.steps.frameworkshakeout.UI' of type java.lang.String to property of type java.util.List -> [Help 1]

[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException

Please help. Thanks

**Comment by mpkorstanje** [comment]
[Migration from version 2.x](https://github.com/temyers/cucumber-jvm-parallel-plugin#migration-from-version-2x)
> The glue property now takes a list of package elements rather then a list of comma delimited packages. A package contains a single package name to be used as glue.

So like this this

```xml
<glue>
  <package>com.example</package>
  <package>com.example.other</package>
</glue>
```

**Comment by gaponte1985** [comment]
Thanks, but the test are not running I have this pom xml 

 <build>
        <plugins>
            <plugin>
                <groupId>com.github.temyers</groupId>
                <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                <version>4.1.0</version>
                <executions>
                    <execution>
                        <id>generateRunners</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>generateRunners</goal>
                        </goals>
                        <configuration>
                            
                            

                            <glue>
                                <package>utilities.java.hooks</package>
                                <package>cukes.steps.frameworkshakeout.UI</package>
                                <package>cukes.steps.frameworkshakeout.API</package>

                            </glue>
                                         
                            
                            <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
                            
                            <featuresDirectory>src/test/resources/features/</featuresDirectory>
                            
                            <cucumberOutputDir>target/cucumber-parallel/</cucumberOutputDir>
                            
                            <format>html</format>
                            
                            <strict>true</strict>
                            
                            <monochrome>true</monochrome>
                            
                            <tags>
                                <tag>@Web</tag>
<tag>API</tag>
                            </tags>
                            
                            
                            <filterFeaturesByTags>true</filterFeaturesByTags>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by mpkorstanje** [comment]
Please show the complete configuration section.

- Are you seeing any errors? 
- Are the test files generated?
- If you remove the tags section do you see any test files generated?

**Comment by gaponte1985** [comment]
no error, test are not generated, but files is beening generated

**Comment by gaponte1985** [comment]
<build>
        <plugins>
            <plugin>
                <groupId>com.github.temyers</groupId>
                <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                <version>4.1.0</version>
                <executions>
                    <execution>
                        <id>generateRunners</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>generateRunners</goal>
                        </goals>
                        <configuration>
                            
                            

                            <glue>
                                <package>utilities.java.hooks</package>
                                <package>cukes.steps.frameworkshakeout.UI</package>
                                <package>cukes.steps.frameworkshakeout.API</package>

                            </glue>
                            
                            
                            <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
                            
                            <featuresDirectory>src/test/resources/features/</featuresDirectory>
                            
                            <cucumberOutputDir>target/cucumber-parallel/</cucumberOutputDir>
                            
                            <format>html</format>
                            
                            <strict>true</strict>
                            
                            <monochrome>true</monochrome>
                            
                            <tags>
                                <tag>@Web</tag>
                                <tag> @API</tag>
                            </tags>
                            
                            
                            <filterFeaturesByTags>true</filterFeaturesByTags>
                            <useTestNG>false</useTestNG>
                            
                            <namingScheme>simple</namingScheme>
                            
                            <namingPattern>Parallel{c}IT</namingPattern>
                            
                            <parallelScheme>FEATURE</parallelScheme>
                            
                            
                            
                            <packageName>com.example</packageName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

**Comment by gaponte1985** [comment]
out put:

WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.uhc.coretestautofrmwk:QAAutomation:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.tngtech.java:junit-dataprovider:jar -> duplicate declaration of version 1.12.0 @ line 192, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.mkolisnyk:cucumber-runner:jar -> duplicate declaration of version 1.0.8 @ line 197, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: junit:junit:jar -> duplicate declaration of version 4.12 @ line 225, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: xml-apis:xml-apis:jar -> version 2.0.2 vs 1.4.01 @ line 237, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building QAAutomation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- cucumber-jvm-parallel-plugin:4.1.0:generateRunners (generateRunners) @ QAAutomation ---
[WARNING] The format parameter is deprecated. Please use plugins
[INFO] Adding /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/generated-test-sources/cucumber to test-compile source root
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ QAAutomation ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ QAAutomation ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ QAAutomation ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 23 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ QAAutomation ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 20 source files to /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ QAAutomation ---
[INFO] Surefire report directory: /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@506e6d5e
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.314 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.864 s
[INFO] Finished at: 2017-06-06T17:56:27-04:00
[INFO] Final Memory: 32M/321M
[INFO] ------------------------------------------------------------------------
LAMU02TC0F2GTFM:com.uhc.coretestautofrmwk gaponte2$

**Comment by mpkorstanje** [comment]
```
                        <tags>
                            <tag>@Web</tag>
                            <tag> @API</tag>
                        </tags>
```

There is a space before the @API.

Also try without the tags.

**Comment by mpkorstanje** [comment]
Also note that these are integration tests (they end with IT.java). These are ran by maven failsafe, not surefire. So you need to run at least maven verify.

**Comment by gaponte1985** [comment]
I fix the space issue, also run mvn verify but still same respond, when you say that generates integration test (it.java) what do you meant?

**Comment by mpkorstanje** [comment]
You should see files in `/Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/generated-test-sources/cucumber`. If you see these files this plugin works fine and you need to configure maven properly.

If these files have a name that end with `Test.java` then they are executed by the maven surefire plugin in the test phase of maven. If the files end with "IT.java" they are executed in the verify phase by the maven failsafe plugin. Unless you specified other defaults.

https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference

---

Anyway your output can't possibly be the same if you run `maven verify`. Please do show the full output.

**Comment by gaponte1985** [comment]
<img width="323" alt="screen shot 2017-06-08 at 8 59 28 am" src="https://user-images.githubusercontent.com/996659/26929787-f0ac0294-4c28-11e7-99e6-54c63cb90f6a.png">

**Comment by gaponte1985** [comment]
no, file was created

**Comment by gaponte1985** [comment]
<build>
        <plugins>
            <plugin>
                <groupId>com.github.temyers</groupId>
                <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                <version>4.1.0</version>
                <executions>
                    <execution>
                        <id>generateRunners</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>generateRunners</goal>
                        </goals>
                        <configuration>
                            
                            

                            <glue>
                                <package>utilities.java.hooks</package>
                                <package>cukes.steps.frameworkshakeout.UI</package>
                                <package>cukes.steps.frameworkshakeout.API</package>

                            </glue>
                            
                            
                            <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
                            
                            <featuresDirectory>src/test/resources/features/google</featuresDirectory>
                            
                            <cucumberOutputDir>target/cucumber-parallel/</cucumberOutputDir>
                            
                            <format>html</format>
                            
                            <strict>true</strict>
                            
                            <monochrome>true</monochrome>
                            
                            <tags>
                                <tag>@Web</tag>
                                <tag>@API</tag>
                            </tags>
                            
                            
                            <filterFeaturesByTags>true</filterFeaturesByTags>
                            <useTestNG>false</useTestNG>
                            
                            <namingScheme>feature-title</namingScheme>
                            
                            <namingPattern>Parallel{c}IT</namingPattern>
                            
                            <parallelScheme>FEATURE</parallelScheme>
                            
                            
                            
                            <packageName>com.example</packageName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


        </plugins>
    </build>

**Comment by gaponte1985** [comment]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@506e6d5e
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.258 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ QAAutomation ---
[INFO] Building jar: /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/QAAutomation-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.131 s
[INFO] Finished at: 2017-06-08T08:57:02-04:00
[INFO] Final Memory: 44M/529M
[INFO] ------------------------------------------------------------------------
LAMU02TC0F2GTFM:com.uhc.coretestautofrmwk gaponte2$ mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building QAAutomation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- cucumber-jvm-parallel-plugin:4.1.0:generateRunners (generateRunners) @ QAAutomation ---
[WARNING] The format parameter is deprecated. Please use plugins
[INFO] Adding /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/generated-test-sources/cucumber to test-compile source root
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ QAAutomation ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ QAAutomation ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ QAAutomation ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 23 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ QAAutomation ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ QAAutomation ---
[INFO] Surefire report directory: /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@506e6d5e
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.275 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.422 s
[INFO] Finished at: 2017-06-08T09:01:34-04:00
[INFO] Final Memory: 18M/437M
[INFO] ------------------------------------------------------------------------

**Comment by gaponte1985** [comment]
LAMU02TC0F2GTFM:com.uhc.coretestautofrmwk gaponte2$ mvn verify
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building QAAutomation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- cucumber-jvm-parallel-plugin:4.1.0:generateRunners (generateRunners) @ QAAutomation ---
[WARNING] The format parameter is deprecated. Please use plugins
[INFO] Adding /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/generated-test-sources/cucumber to test-compile source root
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ QAAutomation ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ QAAutomation ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ QAAutomation ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 23 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ QAAutomation ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ QAAutomation ---
[INFO] Surefire report directory: /Users/gaponte2/IdeaProjects/com.uhc.coretestautofrmwk/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@506e6d5e
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.256 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ QAAutomation ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.604 s
[INFO] Finished at: 2017-06-08T09:02:07-04:00
[INFO] Final Memory: 21M/511M
[INFO] ------------------------------------------------------------------------
LAMU02TC0F2GTFM:com.uhc.coretestautofrmwk gaponte2$

**Comment by mpkorstanje** [comment]
I'm not seeing failsafe in there. Is it in your pom?

**Comment by Abriti15** [comment]
I am using the latest version of cucumber-jvm-parallel plugin (5.0.0) for which the "filterFeaturesByTags" was removed. But when I add tags to run specific scenarios, my build is successful, but not scripts get executed
