### ISSUE TITLE
How to merge all test reports into one

### ISSUE THREAD

**Issue by jun1983** [temyers/cucumber-jvm-parallel-plugin#124]
Hi there,

Thanks for this awesome plugin first. 

I am facing a problem and hope to find an answer here. Test classes generated based on feature, extent report is created for each feature as well, how can I merge all these test reports into one?

**Comment by temyers** [comment]
This is outside the scope of this plugin, but the structure of the cucumber.json format means you could create a post processor to combine the multiple files into a single json list.

**Comment by temyers** [comment]
For general discussion, please post to the Gitter channel: https://gitter.im/cucumber-jvm-parallel-plugin/

**Comment by mpkorstanje** [comment]
This is not supported at the moment. However implementing #127 would make it possible.
