### ISSUE TITLE
Add Gradle support

### ISSUE THREAD

**Issue by iljapavlovs** [temyers/cucumber-jvm-parallel-plugin#125]
Currently, cucumber-jvm-parallel-plugin only supports Maven. Would be nice to have similar plugin in Gradle. There are some options (e.g. [gradle-cucumber-jvm-plugin](https://github.com/commercehub-oss/gradle-cucumber-jvm-plugin)), but they are not quite the same.

**Comment by mpkorstanje** [comment]
I don't see any reason not to. Most of the Mojo is just passing data and defaults. If you can provide a clean PR that should be no problem. I assume @temyers will have to arrange some credentials with the gradle plugin portal.

**Comment by umesh9690** [comment]
do we have gradle support available yet ??

**Comment by mpkorstanje** [comment]
Not unless you or some one else implements it.

**Comment by cfsavant** [comment]
well is there some way to execute this maven plugin in gradle without making it a plugin?
