### ISSUE TITLE
Add fixed ouput for to plugin configuration 

### ISSUE THREAD

**Issue by mpkorstanje** [temyers/cucumber-jvm-parallel-plugin#127]
As a user of the ExtentCucumberFormatter
[I would like to have all my test results in a single file](https://github.com/temyers/cucumber-jvm-parallel-plugin/issues/120#issuecomment-309991485)
So that I can see the results of my parallel tests more easily.

This means that [Plugin](https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/main/java/com/github/timm/cucumber/generate/Plugin.java) should be extended to handle:

```
<plugins>
    <plugin>
        <name>com.cucumber.listener.ExtentCucumberFormatter</name>
        <output>${project.build.directory}/cucumber-parallel/single-report-for-all-tests.html</output>
    </plugin>
</plugins>
```

Providing either extension or outputDirectory in combination with output should be an error. Output may however contain the pattern `{n}` so a number can be inserted if so desired (for more flexible naming).

**Comment by mpkorstanje** [comment]
I'd write this my self but currently working on other things.

**Comment by mechingineer** [comment]
I am waiting for this thing to be implemented. Could you please help us in getting this expedited?

Thanks in Advance !

**Comment by mpkorstanje** [comment]
@mechingineer the simplest and quickest way to do this would be to clone the repository, implement this functionality and send a pull request.
