### ISSUE TITLE
Strategy for running same tests multiple time across different browser.

### ISSUE THREAD

**Issue by halfo** [temyers/cucumber-jvm-parallel-plugin#128]
N.B. This is not an isssue, rather than, asking for suggestion on test running strategy. Here, all the test refers to UI test.

Hi there, thanks for this awesome plugin. My scenario is that, I've a some tests which need to be run across the latest version of major browsers. And few other tests with `@smoke` tag, that are going to run across a large set of browser.

To achieve that, I can create configure multiple `<execution>`, in each execution I can filter a tag, say `@firefox` and add specific hook for firefox as glue code. The problem is;

- This will bloat my pom.xml with so many execution configuration.
- The scenarios will be bloated with huge amount of annotations.

If I run the tests for each browser at a time, then I'm not taking advantage of all the resources I have available. Is there any solution/strategy for such scenario?

**Comment by halfo** [comment]
A solution, for selenium grid users, can be, instead of configuring the browser/os/platform from code or configuration file, we can make available only those browsers in the hub. And we need to have the ability to run all the tests across all available browsers available in the hub. But this would be a problem for BrowserStack/SauceLabs user.

**Comment by temyers** [comment]
I would suggest separating the types of test you want to run (@smoke, etc) from the browsers you wish to run against.  Configuring which browsers you want would be a command line parameter or something.

Separate each of these into separate `<execution>` sections.  It *does* make the pom larger, but I wouldn't say it was bloat - it's explicit about the different types of test you're running.

You can reduce bloat by extracting the common configuration of the plugin into a `<pluginManagement>` section.  So the execution sections only document the changes to the common configuration.

**Comment by halfo** [comment]
> Configuring which browsers you want would be a command line parameter or something.

The problem with this approach is that, suppose I want to run the tests on IE (windows) and Chrome (linux). If I pass the browser/platform config from command line using maven, then I need to complete the set of tests for a browser at first and then again run the tests with different config for another platform.

I'm not sure if I'm missing something or not.
