### ISSUE TITLE
How to clean up after all parallel runners finished their job?

### ISSUE THREAD

**Issue by olgazadlo** [temyers/cucumber-jvm-parallel-plugin#131]
Hi,

we have just started using this plugin (which is very helpful!), however we are now wondering how to implement cleanup after ALL parallel tests were finished? Do you possibly know if there is any annotation already available? What we want to do is to simply delete all records in the DB, but only after every runner is finished with its job. We are using Cucumber + Serenity in Java.

Many thanks in advance!

**Comment by mpkorstanje** [comment]
I reckon that the setup and tear down of the environment is best left to your build system. For maven you may want to hook something into the `pre-integration-test` and `post-integration-test` phases.

https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html 

For travis.ci you can define a pipe with different stages.

https://docs.travis-ci.com/user/build-stages

But if you must use java have a look at using a custom template. You can add `@BeforeClass` and `@AfterClass` hooks. From these hooks you can call a singleton service that keeps track how many tests are running and if the last one finished destroys the database. 

https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/extents-report/src/test/resources/cucumber-extents-report-runner.java.vm

But given the complexity of that solution would not bother.
