### ISSUE TITLE
Feature file are not running parallel 

### ISSUE THREAD

**Issue by gaponte1985** [temyers/cucumber-jvm-parallel-plugin#132]
Hi I have the following plugin 

<build>

    <plugins>

    <plugin>
        <groupId>com.github.temyers</groupId>
        <artifactId>cucumber-jvm-parallel-plugin</artifactId>
        <version>4.1.0</version>
        <executions>
            <execution>
                <id>generateRunners</id>
                <phase>generate-test-sources</phase>
                <goals>
                    <goal>generateRunners</goal>
                </goals>
                <configuration>
                    
                    
                    <glue>
                        <package>utilities.java.hooks</package>
                        <package>cukes.steps.frameworkshakeout.UI</package>
                        <package>cukes.steps.frameworkshakeout.API</package>
                    </glue>
                    
                    
                    <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
                    
                    <featuresDirectory>src/test/resources/features/google</featuresDirectory>
                    
                    <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
                    
                    <plugins>
                        <plugin>
                            <name>json</name>
                        </plugin>
                        <plugin>
                            <name>com.example.CustomHtmlFormatter</name>
                            <extension>html</extension>
                        </plugin>
                    </plugins>
                    
                    <strict>true</strict>
                    
                    <monochrome>true</monochrome>
                    
                    <tags>
                        <tag>@Web</tag>
                    </tags>
                    
                    <useTestNG>false</useTestNG>
                    
                    <namingScheme>simple</namingScheme>
                    
                    <namingPattern>Parallel{c}IT</namingPattern>
                    
                    <parallelScheme>SCENARIO</parallelScheme>
                    
                   
                    
                    <packageName>com.example</packageName>
                </configuration>
            </execution>
        </executions>

    </plugin>
    </plugins>
    </build>

if run this I have the following output 

[INFO] ------------------------------------------------------------------------
[INFO] Building QAAutomation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
LAMU02TC0F2GTFM:com.uhc.coretestautofrmwk gaponte2$ mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building QAAutomation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ QAAutomation ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ QAAutomation ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 24 source files to /Users/gaponte2/IdeaProjects/bff-core/com.uhc.coretestautofrmwk/target/classes
[INFO] 
[INFO] --- cucumber-jvm-parallel-plugin:4.1.0:generateRunners (generateRunners) @ QAAutomation ---
[INFO] Adding /Users/gaponte2/IdeaProjects/bff-core/com.uhc.coretestautofrmwk/target/generated-test-sources/cucumber to test-compile source root
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ QAAutomation ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 25 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ QAAutomation ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 19 source files to /Users/gaponte2/IdeaProjects/bff-core/com.uhc.coretestautofrmwk/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ QAAutomation ---
[INFO] Surefire report directory: /Users/gaponte2/IdeaProjects/bff-core/com.uhc.coretestautofrmwk/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@60f82f98
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.361 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.101 s
[INFO] Finished at: 2017-07-07T14:42:04-04:00
[INFO] Final Memory: 35M/540M
[INFO] ------------------------------------------------------------------------
LAMU02TC0F2GTFM

**Comment by gaponte1985** [comment]
if I add 

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.20</version>
    <dependencies>
      <dependency>
        <groupId>org.apache.maven.surefire</groupId>
        <artifactId>surefire-junit47</artifactId>
        <version>2.20</version>
      </dependency>
    </dependencies>
  </plugin>
Test run but not in parallel I want to be able to run all my feature file in parellel I have a class runner

**Comment by temyers** [comment]
This plugin generates files to support parallel execution but is not actually involved in the execution.

Failsafe, or Surefire need to be configured to run the files in parallel:

Please refer to:
http://maven.apache.org/surefire/maven-failsafe-plugin/examples/fork-options-and-parallel-execution.html
