### ISSUE TITLE
Build failing for missing class org/apache/commons/lang/StringUtils

### ISSUE THREAD

**Issue by imran0692** [temyers/cucumber-jvm-parallel-plugin#133]
Hi,

I setup the plug-in as described @ https://github.com/temyers/cucumber-jvm-parallel-plugin.
However, I am facing following error, when trying maven build. The issue is same with v1.0.1, 1.2.1 and 4.1.0 as well.

The same project runs successfully(Parallel) in another machine but it does not run one of my particular machine. Can you please help me on this.

Please see error stack trace below,
 
Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:1.0.1:generateRunners (generateRunners) on project Excel_testdata: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:1.0.1:generateRunners failed: A required class was missing while executing com.github.temyers:cucumber-jvm-parallel-plugin:1.0.1:generateRunners: org/apache/commons/lang/StringUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.temyers:cucumber-jvm-parallel-plugin:1.0.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/C113895/.m2/repository/com/github/temyers/cucumber-jvm-parallel-plugin/1.0.1/cucumber-jvm-parallel-plugin-1.0.1.jar
[ERROR] urls[1] = file:/C:/Users/C113895/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[2] = file:/C:/Users/C113895/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar
[ERROR] urls[3] = file:/C:/Users/C113895/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[4] = file:/C:/Users/C113895/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[5] = file:/C:/Users/C113895/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.commons.lang.StringUtils

I am also attaching my POM.xml(as text file) with this issue.

**Comment by imran0692** [comment]
I am also adding the StringUtils dependency in my POM.xml but still facing the issue,
<dependency>
    <groupId>commons-lang</groupId>
    <artifactId>commons-lang</artifactId>
    <version>2.6</version>
</dependency>

<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.1</version>
</dependency>

forgot attaching the POM earlier, so attaching now
[pom.txt](https://github.com/temyers/cucumber-jvm-parallel-plugin/files/1156040/pom.txt)

**Comment by temyers** [comment]
The plugin has a dependency on commons lang:

```
<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.5</version>
</dependency>
```

see [pom.xml](https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/pom.xml)

However, this should not be required by your project pom.  Nor should it conflict with any project dependencies.

What version of Maven and Java are you running?

This looks like a configuration problem, rather than a bug with the plugin - as the integration tests pass successfully under CI.

**Comment by imran0692** [comment]
Thank you so much for your reply :) 

Somehow after deleting the maven repository manually and re-downloading all the dependencies again solved my problem.  so you can closing this issue.
