### ISSUE TITLE
turn off 

### ISSUE THREAD

**Issue by gaponte1985** [temyers/cucumber-jvm-parallel-plugin#134]
There is a way to turn off the plugin? 

Example: If i want to run a other class but dont want to used or create the file from the plugins?

**Comment by mpkorstanje** [comment]
Hey Gerardo, 

this is not a forum to ask basic questions about Maven or  Java development in general. Please try to find a co-worker who can assist you or any of these lovely sites:
- http://maven.apache.org/guides/
- https://stackoverflow.com/
