### ISSUE TITLE
Filter generated classes into non-overlapping groups

### ISSUE THREAD

**Issue by jesperpi** [temyers/cucumber-jvm-parallel-plugin#135]
As a test manager developing using a continuous integration pipeline
I want to run non-overlapping sets of tests in parallel from separate maven executions
So that I can configure parallelisation at the level of my continuous integration tool
So that I do not need to redesign my continuous integration pipeline.

I've created a [first draft](https://github.com/jesperpi/cucumber-jvm-parallel-plugin) for this enhancement, configured as follows:
```
<groupFilter>
  <currentGroup>1</currentGroup>
  <totalGroups>2</totalGroups>
</groupFilter>
```
The above configuration will filter half of the generated classes, whereas the other half would be filtered using the following configuration:
```
<groupFilter>
  <currentGroup>0</currentGroup><!-- N.B. using '2' would give the same result-->
  <totalGroups>2</totalGroups>
</groupFilter>
```
I used the  order in which the classes are created to divide the groups, but based on the comments in the integration tests about execution order not being stable across environments, this might not be stable. I'm planning to amend it to use a hash of the properties of the current feature and scenario. Let me know if you think you know a better way.

**Comment by mpkorstanje** [comment]
I do not think this is the proper solution. 

It tries to solve the problem of which tests to execute in the generate test sources phases. To keep this plugin simple it  should always generate all runners for the cucumber features/scenarios that will be executed. The problem of which tests to execute or how to execute them should be solved in a different lifecycle phase.

I think that the best solution would leverage [surefire/failsafe inclusion and exclusion filters](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html) to execute different tests in different maven profiles. For example:

Profile A:
```xml
<includes>
  <include>*0IT.java</include>
  <include>*1IT.java</include>
  <include>*2IT.java</include>
  <include>*3IT.java</include>
  <include>*4IT.java</include>
</includes>
```

Profile B:
```xml
<includes>
  <include>*5IT.java</include>
  <include>*6IT.java</include>
  <include>*7IT.java</include>
  <include>*8IT.java</include>
  <include>*9IT.java</include>
</includes>
```

This is of-course very unwieldy. So I would not be opposed to seeing the pattern naming scheme be expanded to include a modulo counter to make this easier.

```
<namingScheme>pattern</namingScheme>
<namingPattern>Group{m:6}-Parallel{c}IT</namingPattern>
```
Here `m:6` would be interpreted as a `new ModuloCounter(6)` which counts `0,1,2,3,4,5,0,1,3....`

**Comment by jesperpi** [comment]
Ok, on reflection I agree that what you describe is better. If the generation order is fixed this should be quick to implement. I will do so.
