### ISSUE TITLE
Allow <customVmTemplate> to take package name

### ISSUE THREAD

**Issue by abhishek8908** [temyers/cucumber-jvm-parallel-plugin#138]
Currently the template path tag customVmTemplate only allows path which is relative to the project base directory,therefore for every project the user has to add cucumber-custom-runner.vm file.

If it is a package name,the user does not have to include cucumber-custom-runner.vm   every time he creates a project.

**Comment by mpkorstanje** [comment]
You don't need to include customVmTemplate. It is optional. By default JUnit runners will be generated.
