### ISSUE TITLE
Parallel Execution of feature files - maven-failsafe-plugin vs cucumber-jvm-parallel-plugin

### ISSUE THREAD

**Issue by vikramvi** [temyers/cucumber-jvm-parallel-plugin#139]
Currently I'm using maven-failsafe-plugin to run multiple feature files in parallel with Selenium Grid + nodes ( all running in docker containers )

I've basic questions as below

1.  when to use cucumber-jvm-parallel-plugin ?
2.  what benefits / disadvantages of cucumber-jvm-parallel-plugin over maven-failsafe-plugin  parallel execution ?

Thanks in advance.

**Comment by mpkorstanje** [comment]
You need to use both.  See: https://github.com/temyers/cucumber-jvm-parallel-plugin
> This plugin automatically generates a Cucumber JUnit or TestNG runner for each scenario/feature file found in your project.

**Comment by vikramvi** [comment]
@mpkorstanje Thanks for answer but it's not very clear to me yer, can you please clarify what exact benefits; I will get **instead of just using failsafe plugin** ?

Currently I've below setup
Whenever I create new feature file, I as well create runner class for it.

```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features="src/test/resources/features/List/create_new_list.feature")
public class WLC_List {}
```

**Comment by mpkorstanje** [comment]
> A common approach for running Cucumber features in parallel is to create a suite of Cucumber runners, one for each suite of tests you wish to run in parallel. For maximum parallelism, there should be a runner per feature file.

> This is a pain to maintain and not very DRY.

**Comment by vikramvi** [comment]
Thanks again for your time and clarification.
