### ISSUE TITLE
README: Detailed Configuration section is not pretty clear

### ISSUE THREAD

**Issue by vikramvi** [temyers/cucumber-jvm-parallel-plugin#140]
This section says "...Please refer to the integration tests for example usage:...."

please clarify where are the **integration tests**, adding link or name can be useful for first time users.

Thanks,
Vikram

**Comment by vikramvi** [comment]
@mpkorstanje can you please review

**Comment by mpkorstanje** [comment]
Check the link in the next sentence.

**Comment by vikramvi** [comment]
@mpkorstanje  please refer to attached screen shot, I didn't find any link in the next sentence 
<img width="1434" alt="screen shot 2017-08-08 at 3 04 08 pm" src="https://user-images.githubusercontent.com/308490/29073259-461a510c-7c4b-11e7-80c2-e3b0f1824c22.png">

**Comment by mpkorstanje** [comment]
Ah. Seems we're referring to the integration tests more then once now. By default a maven project keeps the integration tests in [src/it](https://github.com/temyers/cucumber-jvm-parallel-plugin/tree/master/src/it).

**Comment by vikramvi** [comment]
Thanks for clarification.
