### ISSUE TITLE
Multiple json files has been generated while running feature files in parallel. Do we have a report merger to get one html file

### ISSUE THREAD

**Issue by amar-1314** [temyers/cucumber-jvm-parallel-plugin#141]
Im using 
<customVmTemplate>src/main/resources/cucumber-extents-report-runner.java.vm</customVmTemplate>
Once runners are generated using below code to execute
<configuration>
                            <forkCount>${surefire.fork.count}</forkCount>
                            <reuseForks>false</reuseForks>
                            <argLine>-Duser.language=en</argLine>
                            <argLine>-Xmx1024m</argLine>
                            <argLine>-XX:MaxPermSize=256m</argLine>
                            <argLine>-Dfile.encoding=UTF-8</argLine>
                            <useFile>false</useFile>
                            <includes>
                                <include>**/*IT.class</include>
                            </includes>
                            <testFailureIgnore>true</testFailureIgnore>
                        </configuration>

**Comment by mpkorstanje** [comment]
This plugin only generates the runners, it doesn't actually handle test execution or any buildphases that follow after it. You'll have to create a tool that merges the json files yourself. and possibly a maven plugin to go with it.

I find that the cucumber-reporting tools for fairly well with parallel files though:

https://github.com/damianszczepanik
