### ISSUE TITLE
Is it possible to run cucumber jvm parallel and using tags to identify scenarios together?

### ISSUE THREAD

**Issue by AndyRohrs** [temyers/cucumber-jvm-parallel-plugin#144]
Hi,

We are running the cucumber parellel jvm plugin and are attempting to also allow the use of tags in the tests that we have created. We are seeing  a conflict between the tags and the JVM parellel plugin in the for of  a MojoException

**Comment by sugatmankar** [comment]
@Andy as per my experience with JVM Parallel plugin, please use it with JUnit for best support.

Qmetry default supported for TestNG, also it won't allow to execute cucumbers before and after listener tags.

**Comment by mpkorstanje** [comment]
Yes. See the integration tests. For example: https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/filter-by-tag/pom.xml
