### ISSUE TITLE
generateRunners goal fails when there are no features

### ISSUE THREAD

**Issue by vilkg** [temyers/cucumber-jvm-parallel-plugin#147]
Hi! 

I noticed that plugin was causing compilation error because I didn't have any features yet : 
Error: 

`Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:4.2.0:generateRunners (generateRunners) on project $name: Features directory does not exist -> [Help 1]`

I think the expected behavior would be to just not generate any runners. What do you think? 

I could help with PR if you agree with my suggestion!

**Comment by temyers** [comment]
My train of thought at the moment is:
* If I'm adding the plugin I'm going to add feature files
* If there aren't any feature files then I should write one - failing build is OK (Red)
* Once I've written one then it should generated runners (Green - failing/pending tests is a *pass* for this scenario) - I can checkin/commit
* Now I have a feature file, then I should implement the test (Refactor)

This is different from:
* I have some feature files
* I've configured to point to the wrong directory
* No runners are generated
* The build "succeeds", but I'm not actually running my tests

Thoughts?

**Comment by temyers** [comment]
Or in another way - the error states the "directory" doesn't exist - again, I'd consider that to be a failure case - the plugin is configured to point to "/src/main/features", but the directory is not found - then it's a configuration issue (I'm pointing to the wrong directory, or I haven't created it yet).

**Comment by vilkg** [comment]
Normally yes, of course, you will add plugin when you have tests. Unless you are building a framework and are not in a stage of tests yet, which happened to me. :) 

I guess it's a matter of taste, but I would say: 

- I configure the directory;
- If there's nothing in that directory - no runners are generated, info message logged;
- If I know I have tests - I am informed that I should double check my dir config and I do that;
- If I know I don't have tests - I won't look for runners. I don't have compilation errors, I can perform sonar analysis, other stages of my pipeline and I am happy.  :)

**Comment by temyers** [comment]
In this case:
1. The directory should still exist - otherwise it's a config error (part of your framework config).  An empty directory is ok, but it must exist (with .gitinclude)
2. Optionally - include a sample feature file.

Are you saying, that the directory exists but the error is still generated?

**Comment by vilkg** [comment]
Nop, directory doesn't exist, since empty directories doesn't really make sense. 

Thanks for recommendations though,  I will just fork. :)

**Comment by mpkorstanje** [comment]
Looking at how other maven plugins treat this scenario I think the proper behavior would be to log the fact that the directory did not exist of that no features were found and move on. E.g. mvn compile works fine even when there is no source code.

**Comment by temyers** [comment]
Good point,

In that case I'd expect:

```
Scenario: Features directory configured does not exist
Given the features directory doesn't exist
When I perform a build
Then a warning log message should be created
But the build should succeed
```

```
Scenario: Features directory is empty
Given the features directory is empty
When I perform a build
Then a warning log message should be created
But the build should succeed
And no runners should be generated
```

@vilkg would be great for a contribution.

Thanks

**Comment by telangn** [comment]
I am having the same error, but my feature files exist within src/test/resources (per instructions what is default within the root of the classpath yes?)
_Issue no. - Running in Docker gives me an error #185 _
When run it passes, but when run within a docker image I get that error.
