### ISSUE TITLE
Latest version not compatible with latest cucumber version

### ISSUE THREAD

**Issue by deepthi-ravindra1** [temyers/cucumber-jvm-parallel-plugin#148]
Hello,

I use cucumber jvm parallel plugin with serenity. I need to use the latest version of serenity which has the latest version of cucumber - 2.0.1.

But, the latest version of cucumber-jvm-parallel-plugin uses an old version of io.cucumber.gherkin (3.2.0), which is presumably not compatible with the latest version of cucumber (2.0.1).

So I have had to downgrade my cucumer-jvm-parallel-plugin version to 1.3.0.

Version 1.3.0 of cucumber-jvm-parallel-plugin has no dependency on cucumber at all, which is why it works.

Can you please update the latest version to use latest cucumber version?

Cheers.

**Comment by vikramvi** [comment]
@deepthi-ravindra1 Do you have any share sample project showing Serenity + Cucumber-jvm-parallel-plugin ?

**Comment by deepthi-ravindra1** [comment]
not a sample project.. but i can send you pom file?

**Comment by deepthi-ravindra1** [comment]
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.6.6</serenity.version>
        <serenity.cucumber.version>1.5.15</serenity.cucumber.version>

        <browserstack.local.version>1.0.2</browserstack.local.version>
        <rest.assured.version>3.0.2</rest.assured.version>
        <open.csv.version>3.8</open.csv.version>
        <log4j.version>1.2.17</log4j.version>
        <jsch.version>0.1.54</jsch.version>
        <java.faker.version>0.13</java.faker.version>
        <jdk.source.version>1.8</jdk.source.version>
        <jdk.target.version>1.8</jdk.target.version>
        <webdriver.provided.mydriver>drivers.BrowserStackSerenityDriver</webdriver.provided.mydriver>
        <cucumber.options></cucumber.options>
        <store.url></store.url>
        <webdriver.perf.driver></webdriver.perf.driver>
        <management.url></management.url>
        <browserstack.only>false</browserstack.only>
        <browserstack.local>true</browserstack.local>
        <browser>chrome</browser>
        <parallelScheme>FEATURE</parallelScheme>
        <environment>SIT</environment>
        <baseStore></baseStore>
        <cucumberRunnerTemplate>cucumber-browserstack-runner.vm</cucumberRunnerTemplate>
        
        <runners>**/*IT.class</runners>
        <featuresDirectory>src/test/resources/features/</featuresDirectory>
        <surefire.rerunFailingTestsCount>3</surefire.rerunFailingTestsCount>
    </properties>


    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>com.browserstack</groupId>
            <artifactId>browserstack-local-java</artifactId>
            <version>${browserstack.local.version}</version>
        </dependency>
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>${open.csv.version}</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>${java.faker.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.temyers</groupId>
            <artifactId>cucumber-jvm-parallel-plugin</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.surefire</groupId>
            <artifactId>surefire-junit4</artifactId>
            <version>2.20.1</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-requirements-provider</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>1.2.0</version>
        </dependency>
        
        
        
        
        
        <dependency>
            <groupId>com.neotys.rest</groupId>
            <artifactId>neotys-rest-api-dataexchange-client-olingo</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-firefox-driver</artifactId>
            <version>3.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.5.3</version>
        </dependency>
        
        
        
        
        
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.temyers</groupId>
                <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                <version>4.2.0</version>
                <executions>
                    <execution>
                        <id>generateRunners</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>generateRunners</goal>
                        </goals>
                        <configuration>
                            <glue>
                                <package>stepdefs</package>
                            </glue>
                            <outputDirectory>${project.build.directory}/generated-test-sources/cucumber
                            </outputDirectory>
                            <featuresDirectory>${featuresDirectory}</featuresDirectory>
                            <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
                            <strict>true</strict>
                            <monochrome>true</monochrome>
                            
                            <useTestNG>false</useTestNG>
                            <namingScheme>feature-title</namingScheme>
                            
                            <parallelScheme>${parallelScheme}</parallelScheme>
                            <customVmTemplate>src/test/resources/cucumberTemplates/${cucumberRunnerTemplate}
                            </customVmTemplate>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20.1</version>
                <executions>
                    <execution>
                        <id>create-test-users</id>
                        <phase>test</phase>
                    </execution>


                </executions>
                <configuration>
                    <includes>
                        <include>testSetup/TestSetup.java</include>
                    </includes>
                    <reuseForks>true</reuseForks>
                    <forkCount>1</forkCount>
                    <testFailureIgnore>true</testFailureIgnore>
                    <systemPropertyVariables>
                        <store.url>${store.url}</store.url>
                        <management.url>${management.url}</management.url>
                        <browserstack.only>${browserstack.only}</browserstack.only>
                        <browserstack.local>${browserstack.local}</browserstack.local>
                        <browser>${browser}</browser>
                        <environment>${environment}</environment>
                        <webdriver.provided.mydriver>${webdriver.provided.mydriver}</webdriver.provided.mydriver>
                    </systemPropertyVariables>
                    <skip>${skipUnit}</skip>
                </configuration>


            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.20.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includes>
                        <include>${runners}</include>
                    </includes>
                    <parallel>classes</parallel>
                    <useUnlimitedThreads>true</useUnlimitedThreads>
                    <forkMode>once</forkMode>
                    <reuseForks>true</reuseForks>
                    <systemPropertyVariables>
                        <serenity.browser.width>1440</serenity.browser.width>
                        <serenity.browser.height>1440</serenity.browser.height>
                        <store.url>${store.url}</store.url>
                        <management.url>${management.url}</management.url>
                        <browserstack.only>${browserstack.only}</browserstack.only>
                        <browserstack.local>${browserstack.local}</browserstack.local>
                        <baseStore>${baseStore}</baseStore>
                        <browser>${browser}</browser>
                        <environment>${environment}</environment>
                        <cucumber.option>${cucumber.options}</cucumber.option>
                        <webdriver.provided.mydriver>${webdriver.provided.mydriver}</webdriver.provided.mydriver>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}
                        </surefire.rerunFailingTestsCount>
                    </systemPropertyVariables>
                    <skipTests>${skipIT}</skipTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>1.6.4</version>
                <executions>
                    <execution>
                        <id>test-setup</id>
                        <phase>test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


    <profiles>
        <profile>
            <id>SMOKE_DEV</id>
            <properties>
                <environment>smoke</environment>
                <browser>chrome</browser>
                <cucumber.options>--tags @smoke</cucumber.options>
                <parallelScheme>FEATURE</parallelScheme>
            </properties>
        </profile>

**Comment by deepthi-ravindra1** [comment]
But with the older version, I cant use parallel scheme and customVmTemplate tags :( which defies the use of parallel plugin. Please fix it asap??

**Comment by vikramvi** [comment]
@deepthi-ravindra1 cucumber-jvm-parallel-plugin latest version is 4.2.0 but above pom.xml has 1.3.0, can you update and check again ?

**Comment by deepthi-ravindra1** [comment]
yes as I said I was using 4.2.0, but since it didn't work with latest serenity version, I had to revert it to an older version

**Comment by temyers** [comment]
contributions welcome.

**Comment by deepthi-ravindra1** [comment]
So are you going to fix this??

**Comment by temyers** [comment]
@deepthi-ravindra1 since this is an issue affecting you, and you know the issue, please fork, fix and submit a PR.

**Comment by mpkorstanje** [comment]
I am currently using `cucumber-jvm:2.1.0` in combination with `cucumber-jvm-parallel-plugin:4.2.0` and it works. Without a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) it will be very hard for anyone (including yourself) to help you.

**Comment by mpkorstanje** [comment]
https://github.com/temyers/cucumber-jvm-parallel-plugin/pull/165 has updated gherkin to 5.0.0
