### ISSUE TITLE
name the generated java class according to the feature files

### ISSUE THREAD

**Issue by vincent-fuchs** [temyers/cucumber-jvm-parallel-plugin#15]
Hi,

I've started to work on a small enhancement that would use the feature file names to generate classes with that name (camelCased), as the current behavior generates 1 class per feature file, but with a generic name. 

This is the main change : 
https://github.com/vincent-fuchs/cucumber-jvm-parallel-plugin/commit/c3590d3f98e20367de2afc69b282cbf683b3e273 

The problem is that currently it breaks most of the existing tests, since the output file is different. 

Do you think this could be useful ? maybe we can add a flag in the config to enable that feature (disabled by default), so that it doesn't impact existing users...

If you're ready to take that feature, I'll fix the tests in my PR, then submit.

**Comment by temyers** [comment]
Interesting.

My first question is why?  What's the need?  Just trying to understand the requirement.

My rationale around the generated names was I wanted something as simple as possible that would be robust.  Since the tests are generated content I didn't see the name as important.  The cucumber report would be the same.

I see a few issues that would need to be considered first:
* There examples that might currently generate invalid names:
| 123-my-feature.feature |
* What about non-latin characters?  Realised that you can have non latin class names.  So this might not be an issue :)
* Changing the class names may change the order of execution.  Could that be an issue?  
** The current plugin makes no guarantees on execution order (intentional).
* What about duplicate feature file names?  Contrived example:
```
  * epic1/feature1.feature
  * epic2/feature2.feature
```
** All tests are generated in the same package so the above would overwrite one of the features.

**Comment by vincent-fuchs** [comment]
I'm thinking this could be useful to investigate potential issues due to parallel run of feature files. Right now, my logs show something like this :

    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running Parallel03IT
    Running Parallel02IT
    Running Parallel01IT
    Running Parallel04IT

In case of a failure, due to the impact of one test on another, it could be convenient to know which test (ie feature file) is actually running. 

for the points you mention :
- for non-latin / invalid characters : this can probably be addressed by first replacing everything that is not [A-Za-z ]* by "x". Then we upper-case the first character of the string, camelCase the rest and we should get something valid.
- for order of execution : just like current behavior no assumption is done. order of execution will probably be different, but if it fails because of this, then it's an issue with the tests having a side effect on each other, not with the plugin
- in my example, I still add a number at the end, just like in current code, to avoid the duplicate class issue.

**Comment by temyers** [comment]
Ok, seems like it could be a good addition.

I'd like the following:
* It should be configurable - a naming scheme property with the following values allowed: simple (default), feature-title
  * From an implementation PoV a NamingSceme interface, with separate implementations for each type.
  * Simple will continue with the ParallelXX convention currently
  * feature-title will use your new implementation

Example:
```<configuration>
         <!-- The Naming Scheme to use. --> 
         <namingScheme>simple</namingScheme>
      </configuration>
```

* Naming conventions to follow:
  * Non latin class names are preserved
  * features starting with a number are prefixed by _
  * One up numbering
Examples:
| Feature title(s) | Example sourcefile |
| Avýplňový.feature | Avýplňový1.java |
| 123.feature | _1231.java |
| a/foo.feature, b/foo.feature | foo1.java, foo2.java |

Anything else to cover?

**Comment by vincent-fuchs** [comment]
looks good to me, I've implemented it. I'll be on leave for one week, I'll push the changes when I'm back, beginning of April

**Comment by bhattankit** [comment]
This could be a good addition. Can we also add functionality to add suffix to the generated class. The reason for this is that we have a couple maven profile that isolates the kind of tests to run.

**Comment by temyers** [comment]
Fixed by pr#18.

Thanks for the contribution.

Included in 1.2.0-SNAPSHOT.  I'll release shortly.

**Comment by temyers** [comment]
Version 1.2.0 released

**Comment by temyers** [comment]
@vincent-fuchs I have created a failing integration test using the new naming scheme.  The generated Class Name has not been updated.

Please fix and submit a pull request.

**Comment by temyers** [comment]
Commit: 0aa0d6667875103c1e64edf2c21d04d397814088
