### ISSUE TITLE
Cucumber "#language"-Tag does not seem to be recognized (anymore?)

### ISSUE THREAD

**Issue by froemra** [temyers/cucumber-jvm-parallel-plugin#150]
I am upgrading from plugin Version 1.3.0 to 4.2.0. I did all the migrations you docoumented to my maven pom. Now, when generating the runners, the cucumber #language-Tag does not seem to be recognized (we are using feature files in german, which is supported by cucumber. This worked fine in 1.3.0, but now I am getting errors like:

```
[ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:4.2.0:generateRunners (generateRunners) on project test-stest: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:4.2.0:generateRunners failed: Parser errors:
[ERROR] (5:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Funktionalität: Anwendungsfall 1'
[ERROR] (7:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Szenariogrundriss: Vorbedingungen'
[...]

```
It seems like the plugin is expecting "Feature:" where we use "Funktionalität:" which is the german version.
I am curious, as this worked with 1.3.0.

Any Ideas?

Cheers,
Ray

**Comment by froemra** [comment]
I narrowed the problem down a little bit: It's broken since V2.0.0. My guess is, this linked to "PR #68 - Support generating runners per scenario". My guess is, the .feature-files are scanned hardcoded for englisch keywords?

**Comment by froemra** [comment]
Did a little bit more of research: The plugin uses cucumber to parse the feature files since 2.0. I guess the language setting is not set correctly within the gherkin parser, otherwise it should work. Don't know exactly how its done, maybe you could look into it?

Cheers,
Ray

**Comment by mpkorstanje** [comment]
Could you create a failing integration test in the src/it/ folder?

**Comment by froemra** [comment]
Yeah, I really tried that. Dependency issues etc when running the existing it-tests, I do not know how people configure that stuff to run correctly. All the maven poms are empty/templates, so this seems to need Configuration in IntelliJ directly. I usually don't do that, thus do not know how ...

But it should be really easy: Just copy an existing test and replace the tags with german tags. E.g. for "simple-it":

```
#language:de
Funktionalität: Feature1

  Szenario: Generate Junit Runner for each feature file
    Gegeben sei I have feature files
    Wenn I generate Maven sources
    Dann the file "target/generated-test-sources/1IT.java" should exist
    Und it should contain:
    """
    @RunWith(Cucumber.class)
    @CucumberOptions(
        strict = true,
        features = {"classpath:features/feature1.feature"},
        format = {"json:target/cucumber-parallel/1.json",
    "pretty"},
        monochrome = false,
        tags = {"@complete", "@accepted"},
        glue = {"foo", "bar"})
    public class Parallel01IT {
    }
    """
```

**Comment by mpkorstanje** [comment]
You can run the integration tests using `mvn clean install -Prun-its`. 

As is I can't reproduce your problem. If you can't get the integration tests to work a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) in the form of a github project would also help.

**Comment by froemra** [comment]
Ok, I wrote a failing test. I created a branch, but I am not allowed to push it:

`remote: Permission to temyers/cucumber-jvm-parallel-plugin.git denied to froemra.
fatal: unable to access 'https://github.com/temyers/cucumber-jvm-parallel-plugin.git/': The requested URL returned error: 403
`

Need a little help here. Sorry, I am new to guthub :)

**Comment by temyers** [comment]
No problem.

Fork the repository and you can then push your changes to your repository and create a Pull Request from there

**Comment by temyers** [comment]
https://help.github.com/articles/fork-a-repo/

**Comment by froemra** [comment]
Thanks! Just created the request.

**Comment by mpkorstanje** [comment]
@froemra You might want to check your files with a hex-editor. I wouldn't be surprised if you have a Byte Order Marker at the start of your file. Managed to reproduce this error that way.

**Comment by froemra** [comment]
@mpkorstanje 
Thanks for the hint. I just added a bom on my mac, where the build is working. It fails now, but the error message is different from the one i get on my windows machine at work. I guess it is best to close the pull request for now, as this seems to be a local problem on my dev environment.

**Comment by froemra** [comment]
@mpkorstanje 
Thanks for you help! Closing it now.

**Comment by froemra** [comment]
In fact, I did not find a solution. I was sticking to an older Version which worked. Now we switched to gradle, so we need a different solution anyway.
Sorry :(

Cheers,
Ray

**Comment by Ostryak** [comment]
Encoding was the root cause in my case:
when I performed "mvn --version" I got
> platform encoding: Cp1251

I already configured pom.xml to use UTF-8:
`<properties>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>`

when I have changed encoding to UTF8 (in windows: 
>SET MAVEN_OPTS=%MAVEN_OPTS% -Dfile.encoding="UTF-8"

Then plugin executed successfully.

**Comment by froemra** [comment]
Thanks! I’ll give that a try.

Cheers,
Rainer
