### ISSUE TITLE
Conflict with Zephyr Plugin for Jenkins

### ISSUE THREAD

**Issue by DmitryGron** [temyers/cucumber-jvm-parallel-plugin#153]
Hola,
I faced conflict with Zephyr Plugin for Jenkins, means that all xml's sent to zapi can't be processed correctly, so we have unexecuted status in test cases.

Cheers,
DmitryGron

**Comment by mpkorstanje** [comment]
This plugin only generates junit or testng runners. It doesn't do execution or reporting. You may need to check with surefire.

If you do think this is a bug with this plugin please include sufficient information to reproduce the problem.
