### ISSUE TITLE
Execute specific Test through command line

### ISSUE THREAD

**Issue by SimonSchaeferFinReach** [temyers/cucumber-jvm-parallel-plugin#156]
Hi,

I successfully integrated the plugin in my application and everything works fine if I execute
`mvn failsafe:integration-test`

Now I wanted to have the possibility to execute only specific Tests (runner classes). So I followed the failsafe documentation and executed
`mvn -Dit.test=FeatureRunnerTest failsafe:integration-test `
this executed the specified class as expected, but the cucumber-parallel plugin does not seem to trigger, since I get not json output and the different scenarios in the feature file do not get executed in parallel.

So my question is: is the execution of specific tests/runner classes supported by this plugin? And if so how do I do it?

Thank you, 
Simon

**Comment by mpkorstanje** [comment]
This plugin generates runners, and limits the runners created based on `cucumber.options`. It doesn't actually execute the tests. So you'll have to `clean` the old runners first.
