### ISSUE TITLE
Cannot AND multiple tags through command line

### ISSUE THREAD

**Issue by Wreckoning90125** [temyers/cucumber-jvm-parallel-plugin#157]
With the tags element containing multiple tag elements, I have not found a way to AND multiple tags together through the command line. The cucumber options tag property does not seem to work, nor does using the same semantics as in cucumber within a single tag element. There is no way to pass tag _elements_ through the command line. I've created a second tag, with a variable ${tags2}, but a tag element cannot be null, and there is no way to put a placeholder for that variable, so I'm having to always pass -Dtags2=~@notATag or something along those lines through the command line. Am I missing something or is this the case?

**Comment by sureshnath** [comment]
The below command line option is equivalent to @tag1 AND @tag2
> -Dcucumber.options='--tags @tag1 --tags @tag2' 

The below command line option is equivalent to @tag1 OR @tag2
> -Dcucumber.options='--tags @tag1,@tag2'

**Comment by johny2000uwb** [comment]
From version 5, you can use tag expression: https://docs.cucumber.io/tag-expressions
