### ISSUE TITLE
Parallel execution  using  cucumber-jvm-parallel-plugin  - how to get reports

### ISSUE THREAD

**Issue by sam04141** [temyers/cucumber-jvm-parallel-plugin#159]
Hi Experts, 
I am executing my  automation program for multiple real devices, using **cucumber-jvm-parallel-plugin**  currently i cant generate reports using json file becase

1. each scenario new json file creates,
2. even program executes in 2 devices only once json file create per one scenario. seems first json file override from 2nd execution 

Appreciate if you could help me to generate report 
bellow are the MAVEN dependencies which i am using

<plugin>
				<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>4.2.0</version>
				<executions>
					<execution>
						<id>generateRunners</id>
						<phase>validate</phase>
						<goals>
							<goal>generateRunners</goal>
						</goals>
						<configuration>
							
							
							<glue>nz.co.skytv.sporthighlightsautomation.cucumber</glue>
							
							
							<outputDirectory>${project.build.directory}/generated-test-sources/features/${device}
							</outputDirectory>
							
							<featuresDirectory>src/test/resources/</featuresDirectory>
							
							<cucumberOutputDir>target/cucumber-parallel/${device}</cucumberOutputDir>
							
							<format>json</format>
							<tags>
								<tag>@LaunchApp</tag>
							</tags>
				        	
				        	<namingPattern>Parallel{c}IT</namingPattern>
							<parallelScheme>SCENARIO</parallelScheme>
						</configuration>
					</execution>
				</executions>
			</plugin>

**my report plugin is** 

<plugin>
		    <groupId>net.masterthought</groupId>
		    <artifactId>maven-cucumber-reporting</artifactId>
		    <version>3.6.0</version>
		    <executions>
		        <execution>
		            <id>execution</id>
		            <phase>package</phase>
		            <goals>
		                <goal>generate</goal>
		            </goals>
		            <configuration>
		                <projectName>sporthighlightsautomation</projectName>
		                <outputDirectory>${project.build.directory}/Report/${device}_results</outputDirectory>
		                <cucumberOutput>target/cucumber-parallel/</cucumberOutput>
		                <parallelTesting>true</parallelTesting>
		            </configuration>
		        </execution>
		    </executions>
		</plugin>

**"my surefire planing is"**

	<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
				<executions>
					<execution>
						<id>acceptance-test</id>
						<phase>integration-test</phase>
						<goals>
							<goal>test</goal>
						</goals>
						<configuration>
							<forkCount>2</forkCount>
							<reuseForks>true</reuseForks>
							<includes>
								<include>**/*IT.class</include>
							</includes>
						</configuration>
					</execution>
				</executions>
			</plugin>

Appreciate your help on this matter

**Comment by sam04141** [comment]
**cucumber parallel plugin and report plugin are as bellow**

<plugin>
				<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>4.2.0</version>
				<executions>
					<execution>
						<id>generateRunners</id>
						<phase>validate</phase>
						<goals>
							<goal>generateRunners</goal>
						</goals>
						<configuration>
							
							
							<glue>nz.co.skytv.sporthighlightsautomation.cucumber</glue>
							
							
							<outputDirectory>${project.build.directory}/generated-test-sources/features/${device}
							</outputDirectory>
							
							<featuresDirectory>src/test/resources/</featuresDirectory>
							
							<cucumberOutputDir>target/cucumber-parallel/${device}</cucumberOutputDir>
							
							<format>json</format>
							<tags>
								<tag>@LaunchApp</tag>
							</tags>
				        	
				        	<namingPattern>Parallel{c}IT</namingPattern>
							<parallelScheme>SCENARIO</parallelScheme>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
		    <groupId>net.masterthought</groupId>
		    <artifactId>maven-cucumber-reporting</artifactId>
		    <version>3.6.0</version>
		    <executions>
		        <execution>
		            <id>execution</id>
		            <phase>package</phase>
		            <goals>
		                <goal>generate</goal>
		            </goals>
		            <configuration>
		                <projectName>sporthighlightsautomation</projectName>
		                <outputDirectory>${project.build.directory}/Report/${device}_results</outputDirectory>
		                <cucumberOutput>target/cucumber-parallel/</cucumberOutput>
		                <parallelTesting>true</parallelTesting>
		            </configuration>
		        </execution>
		    </executions>
		</plugin>

**Comment by mpkorstanje** [comment]
This plugin only generates the runners based on the input you provide. As you're providing it with: 

```
	                <outputDirectory>${project.build.directory}/Report/${device}_results</outputDirectory>
```

I strongly suspect the problem is located in your configuration. You didn't mention anything about a maven profile or multiple executions of the reporting plugin to ensure it generates a a runner for each device.

If anything you should check if the generated sources are as expected.

Then if you think there is an actuall bug please provide https://stackoverflow.com/help/mcve preferably in the form of github repository.
