### ISSUE TITLE
could I use it for browser compatibility testing using selenium grid ? 

### ISSUE THREAD

**Issue by Gaurang033** [temyers/cucumber-jvm-parallel-plugin#16]
HI, 

for browser compatibility testing using selenium grid i need to pass different parameter for each generate test. 

Would you let me know how can i achieve this ?

**Comment by temyers** [comment]
The approach is the same whether you use the cucumber-jvm-parallel-plugin or not.

You would need to run the test suite multiple times, passing different parameters on the command line.  If some tests are specific to a particular browser/OS then use tags to restrict which tests are executed.
