### ISSUE TITLE
bobcat framework - cucumber parallel plugin

### ISSUE THREAD

**Issue by sreedharsaravanan** [temyers/cucumber-jvm-parallel-plugin#172]
Request help to execute test in parallel. 
I am using bobcat framework and added cucumber parallel plugin.
I am able to create multiple runner file based on tags.
When i execute -MVN test, i am seeing only 2 browser instance, but i have given <forkCount>5</forkCount>.
Attaching my pom screen shot.
Request to let me know where i am wrong
<img width="1615" alt="screen shot 2018-06-25 at 11 52 09 am" src="https://user-images.githubusercontent.com/33815073/41869579-4e2655ec-786e-11e8-8b7f-b20af4a3a68b.png">
<img width="1189" alt="screen shot 2018-06-25 at 11 52 26 am" src="https://user-images.githubusercontent.com/33815073/41869583-52d116a4-786e-11e8-83b6-778823cfab56.png">

**Comment by DeChrish** [comment]
@sreedharsaravanan pls work with me
