### ISSUE TITLE
Can we stop splitting  SCENARIO OUTLINE to scenario?

### ISSUE THREAD

**Issue by DeChrish** [temyers/cucumber-jvm-parallel-plugin#174]
Currently, we have 2 options for parallel-scheme.
1. SCENARIO
2.FEATURE

Issue: Scenario Outline is split to a scenario and it is useful for faster feedback, but i is not helpful in grid. we are forced to have multiple VM;s in cloud.

Ex: Our regression test has 3000 - 4000 tests. if we introduce parallel in scenario level we need 4000 vm's;

If we have option to run Scenario and Scenario Outline, we can save some VM;s.

**Comment by wakaleo** [comment]
This is a blocking issue for running scenarios in parallel with Serenity BDD and cucumber-jvm-parallel-plugin - currently, we can only use the FEATURE mode as when scenario outlines are split into individual scenarios, individual test results get overwritten and it is impossible to reassemble the test execution results into a complete scenario outline report.

**Comment by mpkorstanje** [comment]
@DeChrish you may need to look into a slightly less naive method of assigning tests to VM's. This plugin has some functionality to add a modulo counter to test names. This may help facilitate distribution.

@wakaleo once a scenario is compiled into a set of pickles there is no information about the outline left. Each example becomes it's own individual pickle. You could use their URI to match them back to the original line though.

**Comment by DeChrish** [comment]
@mpkorstanje thanks, is it possible to have "SCENARIOskipOutline" option? Is it a minimal change pl guide- i will try.

**Comment by mpkorstanje** [comment]
I currently don't have the capacity to guide or tutor more people. You can look at this yourself but I reckon you'll find it to be non-trivial. That said, you may want to examine your use case. The need to run test together is a smell.
