### ISSUE TITLE
How to run failed test rerun.txt automatically? Please help

### ISSUE THREAD

**Issue by TariqueKhanANX** [temyers/cucumber-jvm-parallel-plugin#175]
@temyers Please help
 
                            <plugin>
				<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>4.2.0</version>
				<executions>
					<execution>
						<id>generateRunners</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>generateRunners</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/target/runner</outputDirectory>
							<glue>
								<package>com.xxx.stepdefs</package>
								<package>com.xxx.cucumber.hooks</package>
							</glue>
							<featuresDirectory>src/test/resources/feature</featuresDirectory>
							
							
							<strict>true</strict>
							<plugins>
								<plugin>
									<name>json</name>
									<extension>json</extension>
									<outputDirectory>${basedir}/target/cucumberreport/json</outputDirectory>
								</plugin>
								<plugin>
									<name>rerun</name>
									<extension>txt</extension>
									<outputDirectory>${basedir}/target/cucumberreport/rerun</outputDirectory>
								</plugin>
							</plugins>
							<useTestNG>true</useTestNG>
							<namingScheme>pattern</namingScheme>
							<namingPattern>Parallel{c}TestRunner</namingPattern>
							<parallelScheme>FEATURE</parallelScheme>

						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by alinpa** [comment]
👍
