### ISSUE TITLE
unable to aggregate multiple .json/.html into single report(how to do that)

### ISSUE THREAD

**Issue by natkrish** [temyers/cucumber-jvm-parallel-plugin#177]
Hi,
I currently, I have the following set up in my pom. 
However, upon running them using mvn clean compile test - the tests run e2e and also it generates multiple .json/.html file in the above folder. But I need one single report with all the test runs. Can you explain on how I can achieve this? 

![image](https://user-images.githubusercontent.com/12541984/44220329-3576ef80-a176-11e8-971a-0d906e0d017b.png)
![image](https://user-images.githubusercontent.com/12541984/44220371-53dceb00-a176-11e8-9517-6b938f6c2020.png)
![image](https://user-images.githubusercontent.com/12541984/44220379-5dfee980-a176-11e8-954c-ba32e081857b.png)

**Comment by berlinets** [comment]
I have the same questions.

**Comment by berlinets** [comment]
Hi there! You can aggregate all these results by maven-cucumber-reporting plugin

`
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>${maven-cucumber-reporting.version}</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>vdr-tests</projectName>
                            <outputDirectory>${project.build.directory}/cucumber-parallel/cucumber-html-reports</outputDirectory>
                            <cucumberOutput>${project.build.directory}/cucumber-parallel/</cucumberOutput>
                            <parallelTesting>true</parallelTesting>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
`

**Comment by berlinets** [comment]
Hi @natkrish ! You can aggregate all these results by maven-cucumber-reporting plugin

```XML
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>${maven-cucumber-reporting.version}</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>vdr-tests</projectName>
                            <outputDirectory>${project.build.directory}/cucumber-parallel/cucumber-html-reports</outputDirectory>
                            <cucumberOutput>${project.build.directory}/cucumber-parallel/</cucumberOutput>
                            <parallelTesting>true</parallelTesting>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
### It will be looks like

![2018-09-05_18-36-23](https://user-images.githubusercontent.com/8873993/45104386-ae94b180-b13a-11e8-9466-8dd549fc3281.png)
![2018-09-05_18-37-22](https://user-images.githubusercontent.com/8873993/45104440-c9672600-b13a-11e8-962f-526354dea393.png)

**Comment by Rameshwar244** [comment]
Hi @natkrish , 

You can check out below plugin as well.

https://github.com/trivago/cluecumber-report-plugin
