### ISSUE TITLE
Use relative path when generating sources

### ISSUE THREAD

**Issue by pardinn** [temyers/cucumber-jvm-parallel-plugin#178]
I started using this plugin and was able to successfully configure it, in order to run my parallel tests.
The thing is, I'm using [maven-cucumber-reporting](https://github.com/damianszczepanik/maven-cucumber-reporting) to generate my reports, and some of the pages are not being loaded correctly. I've found out that this is happening because the filename is too big and they use the information provided "feature" in order to generate the filenames. Since you are using absolute path in the sources, the path will always be massive and therefore I'll continue to not being able to load the files.
Is there a way to configure the plugin to use the relative path of the feature files, rather than the absolute path? Thanks in advance

**Comment by mpkorstanje** [comment]
Currently not. But it should be something that is easy enough to add yourself and submit a PR for.

**Comment by pardinn** [comment]
Thanks for the reply @mpkorstanje 
I'm pretty new to programming, but I'll give it a try and see if I can implement this on my own
