### ISSUE TITLE
Unable to run Cucumber Scripts in parallel using Cucumber JVM Parallel Plugin on IE11 

### ISSUE THREAD

**Issue by mechingineer** [temyers/cucumber-jvm-parallel-plugin#182]
Hi All,

Has anyone succeeded in running the Cucumber scripts in parallel on IE11 using this plugin.

In my case, the browser fires but the actions performed on the browser are very inconsistent. Tried even using with fork count as 2.

Please help if anyone is able to run the scripts in parallel on IE11.

**Comment by fescobar** [comment]
I think is not related to this plugin. Try to create a simple example with IE without using this plugin and you will see what is the real reason. IE always has a lot of problems to setup.
