### ISSUE TITLE
Does plugin support features on russian gherkin dialect?

### ISSUE THREAD

**Issue by SvetlanaUtina** [temyers/cucumber-jvm-parallel-plugin#186]
Hello everyone! :)
I tried to run my features on russian gherkin dialect and I caught this error (error below).
[INFO] --- cucumber-jvm-parallel-plugin:5.0.0:generateRunners (generateRunners) @ cucumber ---
[WARNING] The format parameter is deprecated. Please use plugins
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.946 s
[INFO] Finished at: 2018-11-09T11:48:13+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:5.0.0:generateRunners (generateRunners) on project cucumber: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:5.0.0:generateRunners failed: Parser er
rors:
[ERROR] (3:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Р¤С?Р?РєС?РёР?Р?Р°Р?: С?Р?С?С?С? Р?Р° С?С?Р?РєС?РёР?Р?Р°Р?, РєР?С?Р?С?С?Р№ С?Р°С?РїР?Р?Р°Р?Р°Р?С?С?С? Р?Р° С?С?С?Р°Р?РёС?Р? Р?С?Р?Р?Р?Рє:'
[ERROR] (4:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '1) С?Р?Р·Р?Р°Р?РёР? Р?С?Р?Р?РєРё'
[ERROR] (5:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '2) С?Р?Р°Р?Р?Р?РёР? Р?С?Р?Р?РєРё'
[ERROR] (6:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '3) РєР?РїРёС?Р?Р?Р°Р?РёР? Р?С?Р?Р?РєРё'
[ERROR] (7:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '4) РїР?С?Р?С?Р?Р? РїР? С?С?С?Р?РєР?'
[ERROR] (9:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Р?С?Р?Р?С?С?С?Р?С?РёС?: Р°С?С?Р?Р?С?РёС?РёРєР°С?РёС? РїР?Р? Р°Р?Р?РёР?Р?Р?'
[ERROR] (10:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Р?Р?Р?Р?Р° Р?Р?Р?С?Р·Р?Р?Р°С?Р?Р?С? РїС?Р?С?Р?Р?РёС? Р°С?С?Р?Р?С?РёС?РёРєР°С?РёС? С? Р?Р?Р?РёР?Р?Р? "qaaestimateadmin" Рё РїР°С?Р?Р?Р?Р? "qa1234"'
[ERROR] (12:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'РЎС?Р?Р?Р°С?РёР№: С?Р?Р·Р?Р°Р?РёР? Р?С?Р?Р?РєРё Рё РїС?Р?Р?Р?С?РєР° С?Р?Р·Р?Р°Р?Р?Р?Р№ Р?С?Р?Р?РєРё'
[ERROR] (13:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Р?С?С?С?С? Р?Р°Р?РёР?Р°Р?Р? Р?Р° РєР?Р?РїРєС? С?Р?Р·Р?Р°Р?РёС? Р?С?Р?Р?РєРё'
[ERROR] (14:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'РўР?Р?Р?Р° Р?Р°РїР?Р?Р?С?Р?Р? Р?С?Р?Р?РєС? С?Р? Р·Р?Р°С?Р?Р?РёС?Р?Рё'
[ERROR] (15:7): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '|РєР?РёР?Р?С?      |РїС?Р?Р?РєС?                |С?РєС?РїР?С?С?         |Р?С?Р?Р?Р?Р?Р?РёР?                     |С?Р·С?Рє|Р?РїРёС?Р°Р?РёР? РїС?Р?Р?РєС?Р°                |С?С?С?Р?РєР°
          |'
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

I run my test with command "mvn test -P aut_default,env_local" in terminal of Intellij IDEA. (I also tried to write the encoding -Dfile.encoding=UTF-8).
File encoding is a UTF-8.
![settings idea](https://user-images.githubusercontent.com/23298545/48253070-75690e00-e417-11e8-8f1c-4f184d5c7891.png)
And this is pom of my project.
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cucumber</groupId>
    <artifactId>cucumber</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <mvn.compiler.plugin.version>3.7.0</mvn.compiler.plugin.version>
        <mvn.surefire.plugin.version>2.21.0</mvn.surefire.plugin.version>
        <aspectj.version>1.8.10</aspectj.version>
        <cucumber.version>4.2.0</cucumber.version>
        <selenium.java.version>3.141.5</selenium.java.version>
        <allure.ashot.version>1.5.4</allure.ashot.version>
    </properties>

    <profiles>
        <profile>
            <id>env_local</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <config.location.env>configuration/env_local.xml</config.location.env>
            </properties>
        </profile>
        <profile>
            <id>aut_default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <config.location.aut>configuration/aut_default.xml</config.location.aut>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${mvn.compiler.plugin.version}</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.temyers</groupId>
                <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                <version>5.0.0</version>
                <executions>
                    <execution>
                        <id>generateRunners</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>generateRunners</goal>
                        </goals>
                        <configuration>
                            <encoding>UTF-8</encoding>
                            <glue>
                                <package>steps</package>
                                <package>helper</package>
                            </glue>
                            <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
                            <featuresDirectory>src/test/resources/features</featuresDirectory>
                            <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
                            <namingPattern>Parallel{c}IT</namingPattern>
                            <monochrome>true</monochrome>
                            <format>html</format>
                            <parallelScheme>FEATURE</parallelScheme>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${mvn.surefire.plugin.version}</version>
                <configuration>
                    <forkCount>2</forkCount>
                    <reuseForks>true</reuseForks>
                    <includes>
                        <include>**/*IT.class</include>
                    </includes>
                    <systemPropertyVariables>
                        <config.location.env>${config.location.env}</config.location.env>
                        <config.location.aut>${config.location.aut}</config.location.aut>
                    </systemPropertyVariables>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.java.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.ashot</groupId>
            <artifactId>ashot</artifactId>
            <version>${allure.ashot.version}</version>
        </dependency>
    </dependencies>

</project>

**Comment by qaschevychelov** [comment]
+
I,ve also struggled with this problem
