### ISSUE TITLE
Add ability to add suffix to the generated classname

### ISSUE THREAD

**Issue by temyers** [temyers/cucumber-jvm-parallel-plugin#19]
Added following comment from @bhattankit in issue#15

> This could be a good addition. Can we also add functionality to add suffix to the generated class. The reason for this is that we have a couple maven profile that isolates the kind of tests to run.

**Comment by temyers** [comment]
@bhattankit What would the suffix be used for?  Can you give me an example of a suffix you'd want?

I'd expect to use tags to isolate the tests to run.  
Using `mvn clean` would identify the files executed on a particular run.
Files are generated on each test run, so you may get unexpected results if files were left lying around.

**Comment by bhattankit** [comment]
@temyers - I was using maven profiles to differentiate between different types of tests (eg. component test vs integration test vs end to end test). For this reason I was creating runners with different suffix and then the profile will include runners with a specific suffix when a particular profile is used to run the test. 

I can use the tags approach as well for this. So I wanted to consult and see if the suffix options would be a good use case.

**Comment by temyers** [comment]
Thanks for the info.
I personally don't think that would be a great use case.  Whilst I'm not against adding a suffix in principal, I think your situation would be better served using tags.  It is a more flexible approach and would appear as part of the reporting.

As I understand it, you would also have to configure the cucumber-jvm-parallel-plugin, *and* the surefire/failsafe plugin as part of each profile.  This would bloat the pom.xml making it harder to read.

**Comment by temyers** [comment]
fixed by pr#33
