### ISSUE TITLE
Cannot build 1.2.0

### ISSUE THREAD

**Issue by thesonofthom** [temyers/cucumber-jvm-parallel-plugin#23]
I get the following error when attempting to use 1.2.0

```
[ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:1.2.0:generateRunners (generateRunners) on project test-project: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:1.2.0:generateRunners failed: A required class was missing while executing com.github.temyers:cucumber-jvm-parallel-plugin:1.2.0:generateRunners: com/google/common/base/CaseFormat
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.temyers:cucumber-jvm-parallel-plugin:1.2.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/kthomson/.m2/repository/com/github/temyers/cucumber-jvm-parallel-plugin/1.2.0/cucumber-jvm-parallel-plugin-1.2.0.jar
[ERROR] urls[1] = file:/C:/Users/kthomson/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[2] = file:/C:/Users/kthomson/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar
[ERROR] urls[3] = file:/C:/Users/kthomson/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[4] = file:/C:/Users/kthomson/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[5] = file:/C:/Users/kthomson/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: com.google.common.base.CaseFormat
```

**Comment by temyers** [comment]
I think this is caused by issue#15.  Please can you retry with 1.2.1-SNAPSHOT?

If it's working I'll release shortly.

**Comment by temyers** [comment]
I have released 1.2.1  
Please could you retry.

**Comment by thesonofthom** [comment]
I'm not seeing 1.2.1 on Maven Repository, so my POM file can't find it.
Can you deploy 1.2.1 to ( http://mvnrepository.com/artifact/com.github.temyers/cucumber-jvm-parallel-plugin )?

**Comment by temyers** [comment]
Sorry, it's released properly now to Maven Central.

Please could you retry.

**Comment by vincent-fuchs** [comment]
It's OK now, I'm able to get 1.2.1 from Maven central.

**Comment by dewanprakash** [comment]
Hi, 

I setup the plug-in as described @ https://github.com/temyers/cucumber-jvm-parallel-plugin. 
However, I am facing following error, when trying maven build. The issue is same with v1.2.0, 1.2.1 and 1.3.0 as well.

> `_Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:1.3.0:generateRunners (generateRunners) on project colspace: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:1.3.0:generateRunners failed: A required class was missing while executing com.github.temyers:cucumber-jvm-parallel-plugin:1.3.0:generateRunners: org/apache/velocity/context/Context_`

Please help!!
