### ISSUE TITLE
[question]how to use plugin tag ?

### ISSUE THREAD

**Issue by saikrishna321** [temyers/cucumber-jvm-parallel-plugin#25]
In the Parallel01IT.java i wouls want to include plugin ={"com.cucumber.listener.ExtentCucumberFormatter:"}

Ideally the Runner would look like 

```
@RunWith(Cucumber.class)
@CucumberOptions(strict = true,
    features = {"classpath:features/MyFeature.feature"},
    format = {"json:target//1.json", "html:target//1.html", "pretty"},
    monochrome = false,
    tags = {"@accepted"},
    plugin = {"com.cucumber.listener.ExtentCucumberFormatter:"},
    glue = { "com.cucumber.stepdefinitions" })
public class Parallel01IT {
}
```

how can i add this ?

**Comment by temyers** [comment]
At the moment, "plugin" isn't supported. :(

I'd happily accept a pull request :)

It shall require an update the the code templates.

So:
* What would be an appropriate default value? ""?
* Is any validation required?
* Should it be a new configuration parameter?

**Comment by saikrishna321** [comment]
@temyers will look into this 👍  

I see format has been deprecated, and suggested is to use plugin. Please refer this 

http://cucumber.github.io/api/cucumber/jvm/javadoc/cucumber/api/CucumberOptions.html

**Comment by JasonSmiley208** [comment]
yup... I don't think it works otherwise

**Comment by JasonSmiley208** [comment]
I created a pull request for this.

**Comment by saikrishna321** [comment]
@JasonSmiley208 @temyers any updates on merging the PR to have plugin option

**Comment by saikrishna321** [comment]
@temyers need help in understanding how the Parallel01T.class is generated, i'm planning to work on PR for plugin so need some info. 

How does glue = { $glue }) , get the values from the pom.xml and generate the Parallel01IT.class with those values?

**Comment by JasonSmiley208** [comment]
@saikrishna321 https://github.com/JasonSmiley208/cucumber-jvm-parallel-plugin/blob/master/src/main/java/com/github/timm/cucumber/generate/CucumberITGenerator.java creates the file.

**Comment by saikrishna321** [comment]
@JasonSmiley208 how does the values get pulled from pom.xml to .vm file formatter

**Comment by JasonSmiley208** [comment]
```
public CucumberITGenerator(final FileGeneratorConfig config, final OverriddenCucumberOptionsParameters overriddenParameters) {
        this.config = config;
        this.overriddenParameters = overriddenParameters;
        initTemplate();
    }
```

This is how the IT Generator gets it. Is that what you are asking?

**Comment by temyers** [comment]
`com.github.timm.cucumber.generate.GenerateRunnersMojo` is called by Maven and the parameters are injected in to the `@Parameter` fields.  

These are fields are exposed as an interface `com.github.timm.cucumber.generate.FileGeneratorConfig`

As @JasonSmiley208 points out, these are passed to `com.github.timm.cucumber.generate.CucumberITGenerator.CucumberITGenerator` which are then populated in the Velocity context for use in the `*.vm files`

**Comment by temyers** [comment]
@saikrishna321 How's it going on this?  Need any help?

Create a pull request showing a failing test.  
Can built up from there.
