### ISSUE TITLE
Add checkstyle rules

### ISSUE THREAD

**Issue by temyers** [temyers/cucumber-jvm-parallel-plugin#34]
In order to support contributions,
As the project owner
I want a consistent codeing style to make merge/review easier.

**Comment by saikrishna321** [comment]
@temyers i have started working on this .. check the style check error 
<img width="1361" alt="screen shot 2016-05-25 at 7 39 48 pm" src="https://cloud.githubusercontent.com/assets/4045041/15542935/75275620-22b0-11e6-8fd7-3d5d394e21d1.png">

**Comment by temyers** [comment]
Great, please can you create a pull request into issue_34 branch and I'll review there.

**Comment by saikrishna321** [comment]
Sure..... I'm still working on fixing the errors after style check ... once done will raise.    Can u tag this as inprogress

**Comment by temyers** [comment]
Create an initial pull request, so I can see the changes - I'd like to compare with my current formatter settings.

**Comment by saikrishna321** [comment]
Sure will do that ..... do u want to have Java doc formatter as part of style check ??

**Comment by temyers** [comment]
At this point, I don't think so.
Can always add it later.

**Comment by saikrishna321** [comment]
@temyers i'm done wit this .. did u get to take a look ?

**Comment by temyers** [comment]
Looks good.  

Thanks for the contribution
