### ISSUE TITLE
SNAPSHOT repository?

### ISSUE THREAD

**Issue by netbrain** [temyers/cucumber-jvm-parallel-plugin#40]
I would like to run the 1.3.0-SNAPSHOT version of the plugin, do you have a repository for development builds?

I tried using jitpack for this, however this failed:

https://github.com/jitpack/jitpack.io/issues/590

**Comment by saikrishna321** [comment]
@netbrain jitpack does not build SNAPSHOT it picks commits and also release tag builds

can you try the below for the latest on master

<dependency>
	    <groupId>com.github.temyers</groupId>
	    <artifactId>cucumber-jvm-parallel-plugin</artifactId>
	    <version>f6d7c3029d</version>
	</dependency>

**Comment by netbrain** [comment]
Thats what im already doing. 

```cucumber-jvm-parallel-plugin-f6d7c3029d.jar), Plugin's descriptor contains the wrong version: 1.3.0-SNAPSHOT -> [Help 1]```

**Comment by netbrain** [comment]
Would be good to have a snapshot repository somehow, either through jitpack (like a nightly build through travis.ci?) or through maven central? Anyhow, for now the workaround was to install the snapshot locally.

**Comment by saikrishna321** [comment]
@netbrain i think we also need to add jitpack as part of cucumber-jvm-parallel plugin .. 

but i would see adding it to maven snapshot repo is a good idea

**Comment by temyers** [comment]
SNAPSHOTS are published to [Sonatype OSS Snapshot Repository](https://oss.sonatype.org/content/repositories/snapshots/):

**Comment by temyers** [comment]
cucumber-jvm-parallel-plugin is published to Maven Central at release time
