### ISSUE TITLE
code coverage plugin is needed?

### ISSUE THREAD

**Issue by saikrishna321** [temyers/cucumber-jvm-parallel-plugin#41]

**Comment by temyers** [comment]
Yes definitely.

This was next on my list after checkstyle.

**Comment by temyers** [comment]
PMD + Findbugs a minimum.

**Comment by saikrishna321** [comment]
@temyers have u evaluated any tool ?

**Comment by temyers** [comment]
I'll merge something shortly

**Comment by temyers** [comment]
Added cobertura unit test coverage report.

Run using:
`mvn site`
