### ISSUE TITLE
Specifying tags with quotation marks complicates maven run configuration.

### ISSUE THREAD

**Issue by netbrain** [temyers/cucumber-jvm-parallel-plugin#42]
The configuration option of tags complicates custom run configurations in maven.

so say i have the property "cucumber.tags", which is injected into the tags configuration of the plugin and i'd like to run my project with `mvn -Dcucumber.tags="@completed", "~@ignored"` then this doesn't work properly.

I've also tried to use singular quotes around the whole expression and escaping the double quotes. The result always seems to be that the last double quote is consumed.

Ideally i'd like to be able to run with `mvn -Dcucumber.tags=@completed,~@ignored` where the plugin then correctly transforms this into "@completed","~@ignored" in when creating the runners.

**Comment by temyers** [comment]
Use `-Dcucumber.options=--tags @completed,~@ignored'` instead to override the tags setting via the command line.

See https://github.com/cucumber/cucumber/wiki/Tags

**Comment by netbrain** [comment]
I see, thank you.
