### ISSUE TITLE
Package setting

### ISSUE THREAD

**Issue by tommywo** [temyers/cucumber-jvm-parallel-plugin#45]
Currently there is no way to set java package for runners.

**Comment by temyers** [comment]
That's true.

But this is generated, throw away code.  

So "why do you care?"

**Comment by tommywo** [comment]
In order to run only generated tests and not other existing tests.
I will submit a pull request on this. :)

**Comment by temyers** [comment]
But why would you only want to run generated tests and not others?

You can achieve the same result by using a naming scheme and tweaking the inclusions in surefire/failsafe.

**Comment by ejahns** [comment]
I also think this would be useful. The testng xml configuration allows you to specify tests at the package level. I would use this plugin to generate tests in a certain package and then could use an testng.xml file that specifies that package.
