### ISSUE TITLE
The conversion from a feature file name to a valid class name preserves the '.' character

### ISSUE THREAD

**Issue by greenhammock** [temyers/cucumber-jvm-parallel-plugin#49]
Hello,
Version 1.2.1. I got errors in generated Java code, when generating names using option namingScheme='feature-title' features, for files like "some.test.feature" The '.' is not a valid character in a Java class name.
Here is what I would like to achieve:
* Given I have a feature file with '.' inside a file name
* And I use option namingScheme='feature-title'
* When I want to generate a runner using cucumber-jvm-parallel-plugin
* Then I get a runner with a class name, where '.' characters are replaced with a character, that can be used inside a Java class name

**Comment by temyers** [comment]
Fixed in 1.3.0-SNAPSHOT

**Comment by temyers** [comment]
1.3.0 has been released
