### ISSUE TITLE
Unable to set no tags

### ISSUE THREAD

**Issue by RichardBradley** [temyers/cucumber-jvm-parallel-plugin#50]
How do I generate runners with no tags?

I have found that if I set the following config:

                        <configuration>
                            <tags></tags>

or 

                        <configuration>
                            <tags>  </tags>

Then `cucumber-jvm-parallel-plugin` generates runners like:

    @CucumberOptions(
        tags = {"@complete", "@accepted"},

However, if I use the following command-line property, it does seem to work:

    mvn -Dcucumber.tags= test-compile

I am using ver 1.2.1

**Comment by sugatmankar** [comment]
Hello,

I am working on it. Now if tags are blank no IT file will be generated.

**Comment by temyers** [comment]
As a workaround, `<tags>"~@ignored"</tags>` should also work.

**Comment by temyers** [comment]
Adding this to version 2.0.0.  Since this requires a breaking change.  
The default value for tags needs to be updated so as to be blank by default.

**Comment by sugatmankar** [comment]
@temyers i have added this changes in [` tagwiseOutlinewise`](https://github.com/sugatmankar/cucumber-jvm-parallel-plugin/tree/tagwiseOutlinewise)

If tags are blank it wont generate any file.

**Comment by temyers** [comment]
@RichardBradley I have pushed a fix for plugin 2.0.0-SNAPSHOT

Please could you confirm it fixes your issue.

**Comment by temyers** [comment]
@sugatmankar I don't think that is the desired behaviour here.  If no tags are specified, then all scenarios should be executed - no explicit filter.

**Comment by sugatmankar** [comment]
Okay got it. I will add it.

**Comment by temyers** [comment]
I have already fixed in PR #54

**Comment by sugatmankar** [comment]
@temyers yes but i have implemented differently in tagwise/outlinewise generation.

**Comment by temyers** [comment]
2.0.0 now released.
