### ISSUE TITLE
Features in src/it/resources generate invalid runners

### ISSUE THREAD

**Issue by RichardBradley** [temyers/cucumber-jvm-parallel-plugin#51]
I have my feature files in `src/it/resources`, as per [the Maven standard layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html)

If I configure `cucumber-jvm-parallel-plugin` like:

                        <configuration>
                            
                            <featuresDirectory>src/it/resources</featuresDirectory>

... then it finds all my feature files, but generates invalid runner files which look like:

    @RunWith(Cucumber.class)
    @CucumberOptions(strict = true,
        features = {"classpath:resources/uk/co/me/my-feature.feature"},
        format = {"json:target/cucumber-parallel/3.json", "pretty"},
        monochrome = true,
        tags = {},
        glue = { "uk.co.me" })
    public class Myfeature03IT {

Which fails at runtime because the feature path should be "`classpath:uk/co/me/my-feature.feature`", not "`classpath:resources/uk/co/me/my-feature.feature`"

Do you know how I can fix this?

TIA

**Comment by RichardBradley** [comment]
If I change the "featuresDirectory" to something like "uk/co/me", it complains "`cucumber-jvm-parallel-plugin:... Features directory does not exist`"

**Comment by temyers** [comment]
Have you tried `<featuresDirectory>src/it/resources/</featuresDirectory>`? (note trailing `/`)

**Comment by RichardBradley** [comment]
> Have you tried `<featuresDirectory>src/it/resources/</featuresDirectory>`? (note trailing /)

Yes, that generates:

    features = {"classpath:resources/uk/co/me/my-feature.feature"},

which fails at runtime (due to the extra "resources/" dir)

**Comment by jchen86** [comment]
@RichardBradley 
Have you tried changing the featuresDirectory to `src/it/resources/uk/co/me"?

Looks like the features directory needs to be a subfolder under `resources` e.g. "src/it/resources/features" for the runners to be generated correctly

**Comment by temyers** [comment]
@RichardBradley 

Sorry, mild brain freeze from my last post.  As @jchen86 points out and highlighted in the README: `The diectory, which must be in the root of the runtime classpath`

So:
<featuresDirectory>src/it/resources/uk/</featuresDirectory>

**Comment by RichardBradley** [comment]
Yes, that seems to work, thanks.
