### ISSUE TITLE
Is it possible to use listeners with testNg runners?

### ISSUE THREAD

**Issue by mpanin** [temyers/cucumber-jvm-parallel-plugin#58]
Hi all,

Basically problem is described in title:
As far as I know there are 2 ways to add listeners to TestNG tests: 1. Using annotations in runner (which is not an option cuz we're not able to customize runners)
2. Using testng.xml - and in this case we're required to provide package or location of test classes using package hierarchy.

As I understand there is no way to add listeners when running testNG?

**Comment by temyers** [comment]
Caveat: I don't use TestNG so not familiar with the options

At the moment, classes are generated in the default package.  Can you supply the default package to the testng.xml?

Otherwise it would require a change to replace the package, or add a mechanism to specify listeners

**Comment by mpanin** [comment]
Answer was pretty simple, so there is 3rd way to add listeners to testNG tests: In POM file, like it described on maven site:
[Maven](http://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html)
So case someone is looking for an external solution for rerun listeners - feel free to use listeners in POM.
