### ISSUE TITLE
Add support for filtering classes generated by the required tags

### ISSUE THREAD

**Issue by temyers** [temyers/cucumber-jvm-parallel-plugin#6]
In a large project, if you only want to run small number of features with a specific tag, classes are still generated for all feature files.

When run in parallel, each Test case has a setup/tear down time which can lead to significant overhead.

Add support for filtering the generated output files to only those features that contain the tags to run.

**Comment by davebassan** [comment]
I suppose the ticket I've just raised duplicates this :-)
