### ISSUE TITLE
sometimes cucumber-jvm can't find the glue code

### ISSUE THREAD

**Issue by tcwmj** [temyers/cucumber-jvm-parallel-plugin#60]
I use testng, having a xml test suite.

the test suite have several feature, each feature have it's test. just like this:

`<suite name="regression_suite" verbose="1" parallel="false" thread-count="3">
    <test name="regression1">
        <parameter name="browser" value="ie"/>
        <parameter name="browser_version" value="8" />
        <classes>
            <class name="F00001"/>
        </classes>
    </test>
    <test name="regression2">
        <parameter name="browser" value="ie"/>
        <parameter name="browser_version" value="9" />
        <classes>
            <class name="F00002"/>
        </classes>
    </test>
    <test name="regression3">
        <parameter name="browser" value="ie"/>
        <parameter name="browser_version" value="10" />
        <classes>
            <class name="F00003"/>
        </classes>
    </test>
</suite>`

sometimes the cases (F00003) running in the end would fail and the log shows glue code was not found while the cases running in the beginning with the same glue code pass

**Comment by tcwmj** [comment]
it seems the cucumber-jvm issue

**Comment by temyers** [comment]
Yes, if the test cases are running, this is either an issue in your implementation or cucumber-jvm
