### ISSUE TITLE
[feature request] Allow users to specify a custom runner template (.vm file) rather than junit or testng

### ISSUE THREAD

**Issue by robertgates55** [temyers/cucumber-jvm-parallel-plugin#61]
At the moment, users can choose between junit and testng formats, which changes the runner-template.vm file used to generate the java.

We have the requirement for our runner file to have some additional annotations (eg the test classes extend from a BaseTest class), and so I've forked this project and implemented a custom template.
(fork is here: https://github.com/Frameworkium/cucumber-jvm-parallel-plugin )

I've tried to create a pull request that allows users to specify a <customVmPath> parameter in their pom - alongside the standard parameters for the plugin - to a vm file in their project. For example, it might be in their /resources/ folder: /resources/custom-runner.vm

However, this doesn't work, as Velocity is unable to find the file on the class path (as presumably it's still looking in it's /resources/ folder?)

What do I need to add to make this work, or could a new feature be implemented to enable this?

**Comment by temyers** [comment]
Hi @robertgates55, thanks for contributing.

The trick will be to add project resources to the plugin classpath (preferred method).

Having a very quick Google, I found the following:
http://stackoverflow.com/questions/13855478/accessing-a-project-resource-from-a-plugin-in-maven

Otherwise, you could look at using an alternate resource loader (FileResourceLoader)
http://velocity.apache.org/engine/1.7/developer-guide.html#resource-loaders

But I'd prefer to stick to the classpath resource loader if possible, to maintain consistency.

**Comment by chris-windwalker** [comment]
Do you need help with this? I can see about getting time allocated for this.

**Comment by robertgates55** [comment]
I'd love help with this - got stuck trying to implement and now been diverted to other things... believe (as above)it should just be a matter of getting the project custom config visible to the plugin somehow

**Comment by chris-windwalker** [comment]
Ok, can you merge in the latest from master and I'll hopefully take a look this week.

**Comment by robertgates55** [comment]
Cool thanks. I've merged the latest from master into my fork.

**Comment by chris-windwalker** [comment]
Ok, I've had a quick look and came up with:

 String template = StringUtils.defaultIfEmpty(
                overriddenParameters.getCustomTemplate(),config.templateType().getTemplate());
        velocityTemplate = VelocityTemplateBuilder.build(
                new PropertiesBuilder().withDefaults().build(), template, config.getEncoding());

I've introduced a TemplateType enum of either JUNIT, TESTNG or CUSTOM
i.e.
  TESTNG("cucumber-testng-runner.vm"),
    JUNIT("cucumber-junit-runner.vm"),
    CUSTOM("cucumber-custom-runner.vm");

What they can still do is specify a particular template if they want to under the property cucumber.template.

So do these changes make sense before I start creating tests for this functionality?

**Comment by robertgates55** [comment]
Sure - fine by me - though can't see how that would solve the issue of it not being able to pull through a user's custom .vm file from their project?

Or maybe I'm missing something!

**Comment by chris-windwalker** [comment]
Oh, that's pom configuration no?

http://maven.apache.org/plugins/maven-remote-resources-plugin/examples/sharing-resources.html

**Comment by robertgates55** [comment]
Possibly - but for all my efforts and various Pom configurations I couldn't
get it to work. If you can get it working with the code we have plus a Pom
change then that'd be great.

**Comment by chris-windwalker** [comment]
Ok, I've pushed my changes so far to here:
https://github.com/chris-windwalker/cucumber-jvm-parallel-plugin

feel free to be a guinea pig.

**Comment by chris-windwalker** [comment]
ok, got it working.  Here's what you do:

inside the plugin declaration in your pom add the dependency to the module with the file (can't be the same project.

**Comment by robertgates55** [comment]
Ok cool. Presumably that means I need to build a separate module though - is there any way to do it within one project and one project & one pom?

**Comment by robertgates55** [comment]
The following does the trick and moves the cucumber-custom-runner.vm file from my project-local resources folder to the /classes folder that the plugin seemingly expects to find it in!:

```xml
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>copy-resources</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <resources>
                                        <resource>
                                            <directory>src/test/resources</directory>
                                            <includes>
                                                <include>**/*.vm</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```

(there may be a neater way of doing this... but either way this is neater than multi-modules and resource-sharing!)

No joy specifying a custom file though - what would the config look like to specify cucumber-custom-runner-2.vm, for example?

**Comment by chris-windwalker** [comment]
If using the plug-in from my repo use <customCucumberTemplate>.  Additional checks would need to be added to ensure correct config.  Like force them specifying <templateType>CUSTOM</templateType> if they specify that etc.

**Comment by chris-windwalker** [comment]
you could always pick my commit that just does the refactoring and none of the other changes if that's all required.

**Comment by chris-windwalker** [comment]
ping @robertgates55 what's the latest?

**Comment by ham1** [comment]
I've been looking into this and I can't find a way to put a file onto the classpath such that the velocity classpath loader in this plugin can see it. However, I have managed to get it working by using the url loaded. I have prefixed it with `file://` so it can load an absolute path. Please see PR.

**Comment by chris-mcc** [comment]
That might be ok because you should be able to pass in ${project.build.resources[0].directory}/file.vm

**Comment by ham1** [comment]
Sorry, yes that's how I've got it working. I should have put this comment here as well as the PR #81:
...
<plugin>
  <groupId>com.github.temyers</groupId>
  <artifactId>cucumber-jvm-parallel-plugin</artifactId>
  <version>2.0.3</version>
  <executions>
    <execution>
      ...
      <configuration>
        ...
        
        <customVmTemplate>${basedir}/src/test/resources/cucumber-custom-runner.vm</customVmTemplate>
      </configuration>
    </execution>
  </executions>
</plugin>
...

**Comment by ham1** [comment]
I've just updated the PR to replace the "url" resource loader with "file", which, by default looks in the current directory which is simpler and works in this use case.

**Comment by ham1** [comment]
Thanks for merging!
Are you able to release a v2.0.3 so we may start using this?
Or is there a way to get 2.0.3-SNAPSHOT via maven central or somewhere else?

**Comment by temyers** [comment]
Sorry, got distracted! :)

I'll release today. It shall be v2.1.0

**Comment by temyers** [comment]
2.1.0 is now released.  It shall be available on Maven Central shortly.

For future reference, SNAPSHOTS are deployed here:
`https://oss.sonatype.org/content/repositories/snapshots/`
