### ISSUE TITLE
How to use before and after class with cucumber-jvm-parallel pluging

### ISSUE THREAD

**Issue by rahullodha85** [temyers/cucumber-jvm-parallel-plugin#64]
I want to use before and after class annotations of junit to execute clean-up actions such as close browser after test. However, the parallel class created by this plugin does not create before and after class in cucumberrunnertest file. I am able to execute clean-up as another cucumber step at the end of my tests but it will be skipped in case of a test failure. So is there a way I can always execute test clean-up regardless of test pass or failure with this plugin?

**Comment by sugatmankar** [comment]
Hello @rahullodha85,
Please go through https://github.com/temyers/cucumber-jvm-parallel-plugin/pull/53.

Template used in "Tagwise parallel rerun" has before class after class implementation, copy repo in your local and modify it as per your requirement.

**Comment by temyers** [comment]
Duplicate of issue #61
