### ISSUE TITLE
Issue with screenshots for the failed tests

### ISSUE THREAD

**Issue by andromeda16** [temyers/cucumber-jvm-parallel-plugin#67]
Hi! I've experienced issue with screenshots display in the Cucumber-JVM-Reports:
if there are 2 failed tests in a suite, 1 screenshot for each test and screenshots look the same visually and a size is the same, then link to the 2nd screenshot doesn't work: link to the 2nd screenshot expands/collapses the 1st screenshot.
![screenshot div](https://cloud.githubusercontent.com/assets/2178468/18948267/126a30a0-863f-11e6-8dee-fbf74ff8eccd.png)
![target img](https://cloud.githubusercontent.com/assets/2178468/18948268/1273c408-863f-11e6-9b0e-d561bac1bf86.png)
Is it a feature or a bug?

**Comment by temyers** [comment]
Does the issue occur if you do not use the parallel plugin?

This looks like an underlying issue with the HTML reports - they are out of scope for the parallel plugin itself, as it just uses the underlying mechanism.
