### ISSUE TITLE
With ParallelScheme set to Feature, duplicated generated Runners are found

### ISSUE THREAD

**Issue by chris-windwalker** [temyers/cucumber-jvm-parallel-plugin#73]
I'm seeing that the plug-in is always generating 10 runners even though there are only four feature files.
It looks like it is creating one runner per scenario going by the number of duplicate runners (it is creating the class ok).

I have the plug-in set-up with:
parallelScheme = FEATURE
filterFeaturesByTags = true
tags = ~ignore

It doesn't matter if filterFeaturesByTags  = false or tags is empty.

I have tried versions 2.0.0 and 2.0.1

**Comment by temyers** [comment]
Fixed in 2.0.2
