### ISSUE TITLE
Inconsistent Filters: [@tag,lineNumber] Only one type [line,name,tag] can be used at once.

### ISSUE THREAD

**Issue by sugatmankar** [temyers/cucumber-jvm-parallel-plugin#76]
Hey @temyers,

I tried new code you merged, Its good in compact have great functionality, however there is issue while generating jUnit Runner class.

1. Pass tags in pom `<tags>"@google"</tags>` 
2. Use property  `<parallelScheme>SCENARIO</parallelScheme>`
3. mvn clean verify.

Expected : 
In feature property if feature file path followed by line number as follow 
`features = {"D:/Test/resources/features/Test.feature:**40**"}`
runner class should not include
`tags = {"@google"},`

![inconsistentfilters](https://cloud.githubusercontent.com/assets/4283293/20296251/d558b4fa-ab2f-11e6-8230-d55e77b71d6b.png)

**Comment by temyers** [comment]
Hey @sugatmankar Is this still an issue in release 2.0.2?

I thought I fixed this in #71

**Comment by sugatmankar** [comment]
@temyers Yes I tried on latest master branch.

**Comment by sugatmankar** [comment]
@temyers  Did you release this fix in maven repo? #85

**Comment by temyers** [comment]
Sorry, it's not released yet.  I'll release ASAP.
There's another PR I was hoping to incorporate too

**Comment by temyers** [comment]
fixed in 2.2.0
