### ISSUE TITLE
parallelScheme FEATURE : Generating runners with number of feature files present in project. Only matching tag runner should get generated. 

### ISSUE THREAD

**Issue by sugatmankar** [temyers/cucumber-jvm-parallel-plugin#77]
pom.xml

```
 <parallelScheme>FEATURE</parallelScheme>
 <tags>"@google"</tags>
 <filterFeaturesByTags>true</filterFeaturesByTags>
```

There is only one feature file has tag @google. but runner classes are generated for non matching or no tags on features file. which is unexpected.

Feature with only matching tag should get filtered.

** Edited
sorry it was mistake from my side. Configuration property  
```
<filterFeaturesByTags>true</filterFeaturesByTags> must be true with 
 <parallelScheme>FEATURE</parallelScheme>
 <tags>"@google"</tags>
```

Still if we use following combination runner should not generate runner for all other non matching or empty Feature tag match.

```
<filterFeaturesByTags>false</filterFeaturesByTags>
 <parallelScheme>FEATURE</parallelScheme>
 <tags>"@google"</tags>
```

**Comment by sugatmankar** [comment]
![shouldskipfeature](https://cloud.githubusercontent.com/assets/4283293/20297066/808572b0-ab34-11e6-8083-1e703e74f1b5.PNG)

You just missed Feature Filter. I'm working on it. will pull new request with `tagFilter.matchingFeature(feature)`

**Comment by temyers** [comment]
Is this still an issue with 2.0.2?

If so, please can you give me an example?  I'm not sure I understand the above.

**Comment by sugatmankar** [comment]
@temyers  Yes.

Lets take an example suppose we have 5 feature files with tag on 3 and 2 are not tagged.

`TestFeature1.feature`
```
@feature1 @smoke
Feature: Feature1
 
 @scenario1
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources

 @scenario2
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources
```

`TestFeature2.feature`
```
@feature2 @smoke
Feature: Feature2
 
 @scenario1
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources

 @scenario2
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources
```

`TestFeature3.feature`
```
@feature3 @smoke
Feature: Feature3
 
 @scenario1
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources

 @scenario2
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources
```

`TestFeature4.feature`
```
Feature: Feature4
 
 @scenario1
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources

 @scenario2
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources
```

`TestFeature5.feature`
```
Feature: Feature5
 
 @scenario1
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources

 @scenario2
  Scenario: Generate Junit Runner for each feature file
    Given I have feature files
    When I generate Maven sources
```

Now if i have setting as
```
<filterFeaturesByTags>true</filterFeaturesByTags> 
 <parallelScheme>FEATURE</parallelScheme>
 <tags>"@smoke"</tags>
```

It should generate runner from only those feature file which have "@smoke" tag.

and if i have setting as

```
<filterFeaturesByTags>false</filterFeaturesByTags>
 <parallelScheme>FEATURE</parallelScheme>
 <tags>"@smoke"</tags>
```

It should not generate runner from all 5 feature files.

Even we are generating runner based on Feature tag it will take much more time to execute scenarios sequentially rather it will good if we don't give user an option to set 
```
<filterFeaturesByTags>false</filterFeaturesByTags>
```
properties true or false , lets keep it only two options

```
 <parallelScheme>FEATURE</parallelScheme>  
 <tags>"@smoke"</tags>
```
In this case we have 3 features with "@smoke" tag but each feature has 2 or more scenario (just example) then lets generator generate runner like if we are running scheme by scenario. i.e for feature1.feature it will generate 2 runner per scenarios , for feature2.feature it will generate 2 runner and so on. But strictly runner should be generated from those feature which has only matching tag from property.

**Comment by mpkorstanje** [comment]
If I understand it correctly then the issue is that filterFeaturesByTags is superfluous. It must always be true when tags are present and has no effect when there are none. It can be set to true without any ill effect.

So removing it would be sensible.

**Comment by sugatmankar** [comment]
@mpkorstanje yes Removing it would be sensible. Thank you.

**Comment by temyers** [comment]
4.0.0 should be available in Maven Central shortly.
