### ISSUE TITLE
Browsers do not close after each runner is done

### ISSUE THREAD

**Issue by airyz** [temyers/cucumber-jvm-parallel-plugin#79]
I am not sure if this is a bug or a setting I am missing but my browsers remain open until all runners complete their tests.  I end up having 20+ open browsers.  Is there any setting to setup the browser to close after each runner complete the task?

This was especially visible when I used `<parallelScheme>SCENARIO</parallelScheme>`

**Comment by sugatmankar** [comment]
closing browser is not a part of this plugin. Make sure your WebDriver has closed after test case finished.

**Comment by temyers** [comment]
@sugatmankar Closing the browser is outside the scope of this plugin, since people may have different requirements.

Closing the browser should be done using a JVM shutdown hook, or `@After` method.
