### ISSUE TITLE
[feature request] Json reports to be named with the device name/info

### ISSUE THREAD

**Issue by foxhound91** [temyers/cucumber-jvm-parallel-plugin#80]
There should be a fature to set a custom name on the json report at the CucumberOptions plugin. Otherwise the reports are named with the fork number and it's not easy to identify the remote device where the test was actually executed.
Would it be possible to rename it with the device platform and browser getting them thorugh system or env properties?

I'm happy to help on this if someone provides some guidance

**Comment by temyers** [comment]
* Fork the repository
* Come up with an example demonstrating the functionality you wish to include.  Create a failing acceptance test based on your example, including it in the `src/it` directory with the expectations for the functionality.  Use one of the existing tests as a starting point.
* Create a pre-emptive pull request and we can take it from there.

**Comment by sugatmankar** [comment]
@foxhound91  Yes this feature we can add. I have added in my local repo. Idea behind this is same as you describe.  To get Device name or Node machine name or Browser Name or Browser version should get reflected in json html reports, to get this done it will be combination of this plugin and your webdriver. WebDriver initialization must be done as per configuration withing Generated Runner Class. i.e. suppose i have 10 node machines and i pass machine wise runner get generated , each machine name appeared on each json/html report on which test executed. 

```
Runner.java 
@BeforeClass
public void InitializeWebDriverConfig(String sDeviceName)
{
   Webdriver driver = new RemoteWebDriver("***********HubURL with sDeviceName************");
}

@Test 
public void Runner()
{
   All cucumber invocation logic goes here...
}

@AfterClass
public void CleanUp(){
   All Clean Up activity goes here.
}
```


@temyers can i add this in separate repo? but it will be involvement of Selenium WebDriver API's.

**Comment by temyers** [comment]
@sugatmankar Interacting with Selenium is outside the scope of the parallel plugin.

This plugin is for generating files for running cucumber scenarios in parallel.  

Being able to set the name of the json report would be acceptable, but that should be blanket for a run and done in config only.

**Comment by sugatmankar** [comment]
Yes i got that. @foxhound91 please use this in your webdriver class. No need to worry about other things.

```
@After
public void AddDeviceToJson(Scenario scenario) {
        scenario.write("This test was executed on device "+ getDeviceName);
}
```

**Comment by mpkorstanje** [comment]
@temyers I think this issue can be closed.

**Comment by temyers** [comment]
Thanks for the investigation.
