### ISSUE TITLE
is it possible not to reuse forks (static evil)

### ISSUE THREAD

**Issue by royv-perion** [temyers/cucumber-jvm-parallel-plugin#83]
hi,

i'm in a situation where i have static webdriver because of specific design (not using cucumber dependency injection). i'm experiencing problems with parallel execution (still under investigation) and my first worry is about the static web driver.
i know that using the cucumber-jvm-parallel-plugin , it uses surefire forks(JVMs) instead of threads which means separate JVM for each feature file BUT it is configured to reuse the forks which may prove problematic with static variables. is it true that its not possible to set reuseForks=false ? (will be ignored by the plugin?)
not reusing the JVM forks will ensure full separation in parallel execution in the current design I have.

Thanks

**Comment by sugatmankar** [comment]
You need to change your webDriver as Shared.

**Comment by temyers** [comment]
Actual execution is outside the scope of the parallel plugin - it only generates the test files.

Execution is generally performed using the surefire/failsafe plugin, so using reuseForks=false should be picked up.
