### ISSUE TITLE
Generate classes by feature creates duplicates

### ISSUE THREAD

**Issue by MaxMaOBJ** [temyers/cucumber-jvm-parallel-plugin#88]
When I using the command 'mvn generate-test-sources' everything is working fine, but when I use the command 'mvn test' the generate classes creates duplicates.

**Comment by temyers** [comment]
What configuration are you using in your POM?

Can you provide a sample project?

**Comment by MaxMaOBJ** [comment]
<plugin>
				<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>2.0.2</version>
				<executions>
					<execution>
						<id>generateRunners</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>generateRunners</goal>
						</goals>
						<configuration>
							<glue>com.automationrhapsody.cucumber.parallel.tests.wikipedia</glue>
							<featuresDirectory>src/test/resources/com</featuresDirectory>
							<cucumberOutputDir>${basedir}/target/cucumber</cucumberOutputDir>
							<format>html</format>
							<parallelScheme>FEATURE</parallelScheme>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by MaxMaOBJ** [comment]
I'm sorry, I found the FEATURE was deprecated.

**Comment by temyers** [comment]
FEATURE is deprecated, in favour of the new SCENARIO scheme.  

FEATURE shall be removed as an option in a future release, but for now it should generate as expected.

Please could you try with the SCENARIO scheme?

**Comment by MaxMaOBJ** [comment]
I updated the plugin to version 2.1.0 an changed the parallelScheme to SCENARIO, when I using the command 'mvn clean generate-test-sources' everything is working fine, bug when I using command 'mvn clean test' the generate classes creates duplicates too
![mvn clean generate-test-sources](https://cloud.githubusercontent.com/assets/24557743/21168444/fad8d1d0-c1ee-11e6-839a-ec741665d120.png)
![mvn clean test](https://cloud.githubusercontent.com/assets/24557743/21168449/fcc8f650-c1ee-11e6-876a-562d7dc34bb3.png)
[cucumber.zip](https://github.com/temyers/cucumber-jvm-parallel-plugin/files/650729/cucumber.zip)

**Comment by MaxMaOBJ** [comment]
[cucumber-parallel.zip](https://github.com/temyers/cucumber-jvm-parallel-plugin/files/651026/cucumber-parallel.zip)
Could you help me to check my project? When I added the maven-surefire-report-plugin into my project the cucumber-jvm-parallel-plugin will be calling twice and else anything is working fine.

**Comment by temyers** [comment]
See http://maven.apache.org/surefire/maven-surefire-report-plugin/usage.html

The reporting plugin should be added to the <report> section - not plugin dependencies.

**Comment by MaxMaOBJ** [comment]
Thanks Temyers.

**Comment by MaxMaOBJ** [comment]
Hi @temyers 

When I using the driver-binary-downloader-maven-plugin plugin the generate classes creates duplicates again.

```
<plugin>
				<groupId>com.lazerycode.selenium</groupId>
				<artifactId>driver-binary-downloader-maven-plugin</artifactId>
				<version>1.0.11</version>
				<configuration>
					<rootStandaloneServerDirectory>${project.basedir}/src/test/resources/selenium_standalone_binaries</rootStandaloneServerDirectory>
					<downloadedZipFileDirectory>${project.basedir}/src/test/resources/selenium_standalone_zips</downloadedZipFileDirectory>
					<customRepositoryMap>${project.basedir}/src/test/resources/RepositoryMap.xml</customRepositoryMap>
					<overwriteFilesThatExist>${overwrite.binaries}</overwriteFilesThatExist>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>selenium</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

Thanks

**Comment by temyers** [comment]
What section is the plugin defined in?

Is sounds like the `generate-test-sources` phase is being called twice.

Can you post debug output:`mvn clean package -X`
