### ISSUE TITLE
Could you please make it for .story file also

### ISSUE THREAD

**Issue by SumantaSarathiChakraborty** [temyers/cucumber-jvm-parallel-plugin#93]
I am facing the same problem but I am using JBehave. So, I use .story file instead of .feature file. 

Could you please check if you can make it work for JBehave projects also. I guess it would be a very small change in this project.

Thanks in advance,

Regards,
Sumanta

**Comment by temyers** [comment]
Contributions welcome.

Although I would suspect that it would be more appropriate to fork the repository and diverge the codebase.

**Comment by mpkorstanje** [comment]
http://jbehave.org/reference/stable/multi-threading.html
> The JBehave Embedder allows concurrent execution of stories. The multi-threading behaviour is controlled by setting the number of concurrent threads (which defaults to 1) via the EmbedderControls, or equivalently via @UsingEmbedder or the Ant tasks or Maven goals.
