### ISSUE TITLE
Extent Report not supported by Cucumber JVM Parallel Plugin

### ISSUE THREAD

**Issue by mechingineer** [temyers/cucumber-jvm-parallel-plugin#95]
I am trying to integrate Extent Report with the Cucumber JVM Parallel Plugin but failed to do so.
After trying a lot, finally took the source code on my system and debugged the issue.
Below is the explanation of the issue:
For Extent Report to generate a report at the end, there need to be a plugin added in the @CucumberOptions in Runner class. See the Example below:
**@CucumberOptions(
		features = {"Feature Files"}
		,glue={"libraries","utilities"}
		,plugin={"libraries.ExtentCucumberFormatter"}
		)**
Here the plugin 'libraries.ExtentCucumberFormatter' is mandatory for creating a report(libraries is the name of the package where ExtentCucumberFormatter Java file lies. ExtentCucumberFormatter.java is the file which is finally responsible for creating the ExtentReport after the test execution).

Now, I am trying to pass the Extent Report Plugin (libraries.ExtentCucumberFormatter) in the format tag in pom.xml as shown below:

        
        <glue>libraries,utilities</glue>
        <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
         
          <featuresDirectory>Feature Files</featuresDirectory>
         
         <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
         
         <format>libraries.ExtentCucumberFormatter</format>** -->

But the runners that are created at RunTime displays the plugin in @CucumberOptions as below:

**@CucumberOptions(strict = true,
features = {"C:/Workspace/Peacock/Feature Files/Test.feature"},
plugin = {"libraries.ExtentCucumberFormatter:target/cucumber-parallel/1.libraries.ExtentCucumberFormatter"},**

I checked in the Source Code, only "pretty" would be printed as it is in the plugin, other than that everything would be formatted in the format shown above.

Now, I know where to make the necessary changes in the code and include my plugin i.e. 'libraries.ExtentCucumberformatter' as it in the plugin of the Runner class, but I am unsure on how to use to use my source code there after.

Please help me in resolving this issue so that I can proceed further with the implementation.

What I finally require in all the runner classes is shown below:

**@CucumberOptions(strict = true,
features = {"C:/Workspace/Peacock/Feature Files/Test.feature"},
plugin = {"libraries.ExtentCucumberFormatter"}**

**Comment by mpkorstanje** [comment]
Having had a look at this I don't think it would be a good idea to add a special case for the ExtentCucumberformatter. Rather I think we should have a look at how the formatter/plugins are driven. 

`@CucumberOptions` uses the format `plugin[:file.extension]`.

The `file.extension` part is parsed by cucumber and provided as an argument to the plugin when present. The file location is already provided by cucumber-jvm-parallel-plugin in the form of the `outputDirectory` property so we only need to provide the name of the plugin and the file extension.

So if we change add a `formats` elements to the configuration that accepts a list of formatter objects we can do this.

```
<formatters>
  <formater>
      <name>path.to.my.CustomHtmlFormatter</name>
      <extension>html</extension>
      <outputDirectory>optional/alternative/output/directory</outputDirectory>
   <formater>
  <formater>
      <name>path.to.my.CustomJsonFormatter</name>
      <extension>json</extension>
      <outputDirectory>optional/alternative/output/directory</outputDirectory>
   <formater>
<formatters>
```

For the html and json formatters we can add some sensible defaults so that they work right away.

```
  <formater>
      <name>html</name>
   <formater>
  <formater>
      <name>json</name>
   <formater>
```

 However not all plugins require arguments so we have to make this optional. We can do this by leaving out the extension attribute.

```
  <formater>
      <name>pretty</name>
   <formater>
```

Additionally if we have multiple plugins that output to json they can not output in the same outputDirectory.

```
<formatters>
  <formater>
      <name>path.to.my.CustomJsonFormatter</name>
      <extension>json</extension>
      <outputDirectory>optional/alternative/output/directory/for/my/custom/json</outputDirectory>
   <formater>
  <formater>
      <name>path.to.my.other.JsonFormatter</name>
      <extension>json</extension>
      <outputDirectory>optional/alternative/output/directory/for/my/other/json</outputDirectory>
   <formater>
<formatters>
```

**Comment by mpkorstanje** [comment]
@mechingineer I reckon #104 should fix this. Could you check out that branch, build it locally and see if it works for you?

**Comment by mpkorstanje** [comment]
@mechingineer this should do the trick. [extents-report/pom.xml](https://github.com/mpkorstanje/cucumber-jvm-parallel-plugin/blob/be7a2bd8f97f97c485e2c76a50925297ccf38574/src/it/junit/extents-report/pom.xml)

**Comment by temyers** [comment]
Merged #104.

Marking this as closed.  

Will release 3.0.0 today.

**Comment by gaponte1985** [comment]
@mpkorstanje  extents-report/pom.xml that link is broken can you please provide another one thanks

**Comment by mpkorstanje** [comment]
https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/extents-report/src/test/resources/cucumber-extents-report-runner.java.vm
https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/extents-report/pom.xml

Beware of https://github.com/temyers/cucumber-jvm-parallel-plugin/issues/127 though. You might want to fix that so all reports end up in a single file.
