### ISSUE TITLE
Parsing Error for scenario outline with commented Examples row.

### ISSUE THREAD

**Issue by jasminprajapati** [temyers/cucumber-jvm-parallel-plugin#96]
When I've got scenario with outline, and I comment all of the table rows, parsing error is seen.

@P2T6
Scenario Outline: Test Scenario
Given Project DC <DC_Center> is available
And I am already logged in with multi-Project user
Given I am on "Projects" tab
And I Search Cloned_Project AND Deactivate
Examples: 
|DC_Center|
#|UK|

Unable to parse above scenario and got error below.

[ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:2.2.0:generateRunners (generateRunners) on project adoddle.p2: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:2.2.0:generateRunners failed: Parser errors:
[ERROR] (155:1): expected: #TableRow, #Comment, #Empty, got '@P2T6'
[ERROR] (156:1): expected: #TableRow, #Comment, #Empty, got 'Scenario Outline: Test Scenario'
[ERROR] (157:1): expected: #TableRow, #Comment, #Empty, got 'Given Project DC <DC_Center> is available'
[ERROR] (158:1): expected: #TableRow, #Comment, #Empty, got 'And I am already logged in with multi-Project user'
[ERROR] (159:1): expected: #TableRow, #Comment, #Empty, got 'Given I am on "Projects" tab'
[ERROR] (160:1): expected: #TableRow, #Comment, #Empty, got 'I Search Cloned_Project AND Deactivate'
[ERROR] -> [Help 1]

**Comment by sugatmankar** [comment]
@jasminprajapati Its not this plugin issue. You are not following Gherkin Best practices. Gherkin don't parse silly mistakes. 

when you are using Examples at least table header and row is expected. if you want to use NULL instead of UK just leave it as blank |  | .

Examples:
|DC_Center|
|UK|
