### ISSUE TITLE
When transferring from SCENARIO parallelScheme to FEATURE, scenarios still run in parallel

### ISSUE THREAD

**Issue by roy-ro** [temyers/cucumber-jvm-parallel-plugin#97]
Hi,
I've noticed that if my POM property of parallelScheme was set to SCENARIO and I switched it to FEATURE, then scenarios continue to run in parallel.

This issue was solved when the cucumber parallel runners, found in the target folder, were deleted after the change. As long as they were not manually deleted, then tests had continued to run as if the parallelScheme was still set to SCENARIO.

Roy

**Comment by temyers** [comment]
This is expected behaviour.

This plugin generates the required class files, overwriting only those it re-generates.

If you wish to remove old generated files, use `mvn clean`

**Comment by roy-ro** [comment]
OK thanks.
Is it documented somewhere? 
It took me a while to understand that this is its behavior.
